"""
Bulky data structures for assertion in pyteomics test suites.
"""

import numpy as np
from copy import deepcopy

# http://stackoverflow.com/q/14246983/1258041
class ComparableArray(np.ndarray):
    def __eq__(self, other):
        if not isinstance(other, np.ndarray):
            return False
        other = np.asarray(other, dtype=np.float)
        return self.shape == other.shape and np.allclose(self, other)

def makeCA(arr):
    return ComparableArray(arr.shape, arr.dtype, arr)

pepxml_spectra = [
            {'spectrum': 'pps_sl20060731_18mix_25ul_r1_1154456409.0100.0100.1',
             'end_scan': 100,
             'start_scan': 100,
             'index': 1,
             'assumed_charge': 1,
             'precursor_neutral_mass': 860.392,
             'search_hit': [{
             'num_missed_cleavages': 0,
             'tot_num_ions': 12,
             'is_rejected': False,
             'search_score': {
                'deltacn': 0.081,
                'sprank': 1.0,
                'deltacnstar': 0.0,
                'spscore': 894.0,
                'xcorr': 1.553},
             'hit_rank': 1,
             'num_matched_ions': 11,
             'num_tot_proteins': 1,
             'peptide': 'SLNGEWR',
             'massdiff': -0.5,
             'analysis_result': [{'analysis': 'peptideprophet',
                 'peptideprophet_result':
                 {'all_ntt_prob': [0.0422, 0.509, 0.96],
                  'parameter':
                    {'fval': 1.4723, 'massd': -0.5, 'nmc': 0.0, 'ntt': 2.0},
                  'probability': 0.96}}],
             'modifications': [],
             'modified_peptide': 'SLNGEWR',
             'proteins': [{'num_tol_term': 2,
                           'protein': 'sp|P00722|BGAL_ECOLI',
                           'peptide_prev_aa': 'R',
                           'protein_descr': 'BETA-GALACTOSIDASE (EC 3.2.1.23) '
                                            '(LACTASE) - Escherichia coli.',
                           'peptide_next_aa': 'F'}],
             'calc_neutral_pep_mass': 860.892}]},
            {'precursor_neutral_mass': 677.392,
             'spectrum': 'pps_sl20060731_18mix_25ul_r1_1154456409.0040.0040.1',
             'start_scan': 40,
             'assumed_charge': 1,
             'index': 2,
             'end_scan': 40,
             'search_hit': [{'tot_num_ions': 10,
             'num_missed_cleavages': 1,
             'is_rejected': False,
             'hit_rank': 1,
             'num_matched_ions': 8,
             'search_score': {
                'sprank': 1.0,
                'deltacn': 0.165,
                'deltacnstar': 0.0,
                'spscore': 427.0,
                'xcorr': 1.644},
             'num_tot_proteins': 1,
             'peptide': 'GKKFAK',
             'massdiff': -0.5,
             'analysis_result': [{'analysis': 'peptideprophet',
              'peptideprophet_result': {
                  'all_ntt_prob': [0.0491, 0.548, 0.9656],
                  'parameter': {
                      'fval': 2.0779, 'massd': -0.5, 'nmc': 1.0, 'ntt': 1.0},
                  'probability': 0.548}}],
             'modifications': [],
             'modified_peptide': 'GKKFAK',
             'proteins': [{'num_tol_term': 1,
                           'protein': 'gi|3212198|gb|AAC22319.1|',
                           'peptide_prev_aa': 'N',
                           'protein_descr': 'hemoglobin-binding protein '
                                            '[Haemophilus influenzae Rd]',
                           'peptide_next_aa': 'I'}],
             'calc_neutral_pep_mass': 677.892}]},
              {'assumed_charge': 2,
             'end_scan': 1366,
             'index': 29,
             'precursor_neutral_mass': 718.4136,
             'retention_time_sec': 38.426123,
             'search_hit': [{'calc_neutral_pep_mass': 718.4126,
               'search_score': {
                   'expect': 0.0,
                   'homologyscore': 46.61,
                   'identityscore': 25.38,
                   'star': 0.0,
                   'ionscore': 36.45},
               'hit_rank': 1,
               'is_rejected': False,
               'massdiff': 0.0011,
               'modifications': [],
               'modified_peptide': 'VGQFIR',
               'num_matched_ions': 5,
               'num_missed_cleavages': 0,
               'num_tot_proteins': 1,
               'peptide': 'VGQFIR',
               'analysis_result': [{'analysis': 'peptideprophet',
                    'peptideprophet_result':
                    {'all_ntt_prob': [0., 0.5741, 0.7264],
                      'parameter': {
                      'fval': 0.6052, 'massd': 0.001, 'nmc': 0.0, 'ntt': 2.0},
                    'probability': 0.7264}}],
               'proteins': [{'num_tol_term': 2,
                 'peptide_next_aa': 'L',
                 'peptide_prev_aa': 'K',
                 'protein': 'IPI00200898',
                 'protein_descr': None}],
               'tot_num_ions': 10}],
             'spectrum': 'MASCOT',
             'start_scan': 1366},
             {'assumed_charge': 2,
             'end_scan': 6862,
             'index': 49,
             'precursor_neutral_mass': 1404.7476,
             'search_hit': [{'search_score': {
                   'bscore': 2.0,
                   'expect': 0.012,
                   'nextscore': 14.6,
                   'hyperscore': 23.5,
                   'yscore': 8.7},
               'calc_neutral_pep_mass': 1404.7435,
               'hit_rank': 1,
               'is_rejected': False,
               'massdiff': 0.004,
               'modifications': [{'mass': 1.0079, 'position': 0},
                   {'mass': 147.0354, 'position': 10},
                   {'mass': 17.0031, 'position': 13}],
               'modified_peptide': 'EVPLNTIIFM[147]GR',
               'num_matched_ions': 8,
               'num_missed_cleavages': 0,
               'num_tot_proteins': 2,
               'peptide': 'EVPLNTIIFMGR',
               'proteins': [{'num_tol_term': 2,
                 'peptide_next_aa': 'V',
                 'peptide_prev_aa': 'R',
                 'protein': 'sp|P01008|ANT3_HUMAN',
                 'protein_descr': 'Antithrombin-III OS=Homo sapiens GN=SERPINC1 PE=1 SV=1'},
                {'num_tol_term': 2, 'protein': 'tr|Q8TCE1|Q8TCE1_HUMAN', 'protein_descr': 'SERPINC1 protein OS=Homo sapiens GN=SERPINC1 PE=2 SV=1'}],
               'tot_num_ions': 22}],
             'spectrum': 'X!Tandem',
             'start_scan': 6862},
            {'assumed_charge': 3,
             'end_scan': 23,
             'index': 3,
             'precursor_neutral_mass': 3254.044921875,
             'search_hit': [{'calc_neutral_pep_mass': 3254.04711914062,
                 'search_score': {
                   'expect': 13690.946579388728,
                   'pvalue': 59.52585469299447},
               'hit_rank': 1,
               'is_rejected': False,
               'massdiff': -0.002197265625,
               'modifications': [{'mass': 166.99803, 'position': 6},
                {'mass': 166.99803, 'position': 7},
                {'mass': 166.99803, 'position': 9},
                {'mass': 160.03019, 'position': 15},
                {'mass': 160.03019, 'position': 21}],
               'modified_peptide': 'DQQFDS[166]S[166]SS[166]MALEDCGEETNCQSDFK',
               'num_matched_ions': 3,
               'num_tot_proteins': 1,
               'peptide': 'DQQFDSSSSMALEDCGEETNCQSDFK',
               'proteins': [{'num_tol_term': 0,
                 'peptide_next_aa': 'I',
                 'peptide_prev_aa': 'R',
                 'protein': 'BL_ORD_ID:125453',
                 'protein_descr': 'sp|O43149|ZZEF1_HUMAN Zinc finger ZZ-type and EF-hand domain-containing protein 1 OS=Homo sapiens GN=ZZEF1 PE=1 SV=6:reversed'}],
               'tot_num_ions': 50},
              {'calc_neutral_pep_mass': 3254.04711914062,
                  'search_score': {'expect': 14837.682803311733,
                   'pvalue': 64.51166436222492},
               'hit_rank': 2,
               'is_rejected': False,
               'massdiff': -0.002197265625,
               'modifications': [{'mass': 243.02933, 'position': 6},
                {'mass': 170.10596, 'position': 8},
                {'mass': 181.01368, 'position': 11},
                {'mass': 181.01368, 'position': 13},
                {'mass': 181.01368, 'position': 18},
                {'mass': 181.01368, 'position': 21},
                {'mass': 160.03019, 'position': 1},
                {'mass': 160.03019, 'position': 4}],
               'modified_peptide': 'CENCNY[243]PK[170]EGT[181]HT[181]NQHET[181]LHT[181]SR',
               'num_matched_ions': 6,
               'num_tot_proteins': 2,
               'peptide': 'CENCNYPKEGTHTNQHETLHTSR',
               'proteins': [{'num_tol_term': 0,
                 'peptide_next_aa': 'S',
                 'peptide_prev_aa': 'R',
                 'protein': 'BL_ORD_ID:144314',
                 'protein_descr': 'tr|Q6ZND3|Q6ZND3_HUMAN Zinc finger protein 184 OS=Homo sapiens GN=ZNF184 PE=2 SV=1:reversed'},
                {'protein': 'BL_ORD_ID:154629', 'protein_descr': 'sp|Q99676|ZN184_HUMAN Zinc finger protein 184 OS=Homo sapiens GN=ZNF184 PE=1 SV=4:reversed'}],
               'tot_num_ions': 44}],
             'spectrum': ' Cmpd 24, +MSn(1085.6886), 1.2 min.23.23.3',
             'start_scan': 23}]

mzid_spectra = {(False, False): [{'id': 'SEQ_spec1',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=1'},
 {'id': 'SEQ_spec2a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=2'},
 {'id': 'SEQ_spec3a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=3'},
 {'id': 'SEQ_spec10',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=10'},
 {'id': 'SEQ_spec11a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=11'},
 {'id': 'SEQ_spec12',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=12'},
 {'id': 'SEQ_spec13',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=13'},
 {'id': 'SEQ_spec15',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=15'},
 {'id': 'SEQ_spec20',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=20'},
 {'id': 'Mas_spec2b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=2'},
 {'id': 'Mas_spec3b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=3'},
 {'id': 'Mas_spec4',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=4'},
 {'id': 'Mas_spec6',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=6'},
 {'id': 'Mas_spec11b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=11'},
 {'id': 'Mas_spec12',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=12'},
 {'id': 'Mas_spec35',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=35'},
 {'id': 'Mas_spec36b1',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=36'},
 {'id': 'Mas_spec40',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=40'}],

(False, True): [{'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=1'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=2'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=3'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=10'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=11'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=12'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=13'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=15'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=20'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=2'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=3'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=4'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=6'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=11'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=12'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=35'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=36'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=40'}],

(True, False): [{'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec1_pep1'}],
    'ProteinScape:IntensityCoverage': 0.3919545603809718,
    'ProteinScape:SequestMetaScore': 7.59488518903425,
    'calculatedMassToCharge': 1507.695,
    'chargeState': 1,
    'experimentalMassToCharge': 1507.696,
    'id': 'SEQ_spec1_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot1_pep1',
    'rank': 1}],
  'id': 'SEQ_spec1',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=1'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec2a_pep1'}],
    'ProteinScape:IntensityCoverage': 0.5070386909133888,
    'ProteinScape:SequestMetaScore': 10.8810331335713,
    'calculatedMassToCharge': 1920.9224,
    'chargeState': 1,
    'experimentalMassToCharge': 1920.923,
    'id': 'SEQ_spec2a_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot1_pep2',
    'rank': 1}],
  'id': 'SEQ_spec2a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=2'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec3a_pep1'}],
    'ProteinScape:IntensityCoverage': 0.43376827663349576,
    'ProteinScape:SequestMetaScore': 6.1021771936508955,
    'calculatedMassToCharge': 864.4752,
    'chargeState': 1,
    'experimentalMassToCharge': 864.474,
    'id': 'SEQ_spec3a_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot1_pep3',
    'rank': 1}],
  'id': 'SEQ_spec3a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=3'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec10_pep1'}],
    'ProteinScape:IntensityCoverage': 0.16164593872706742,
    'ProteinScape:SequestMetaScore': 5.635013787097159,
    'calculatedMassToCharge': 1832.862115,
    'chargeState': 1,
    'experimentalMassToCharge': 1832.863,
    'id': 'SEQ_spec10_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot1_pep4',
    'rank': 1}],
  'id': 'SEQ_spec10',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=10'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec11a_pep1'}],
    'ProteinScape:IntensityCoverage': 0.6146634530945828,
    'ProteinScape:SequestMetaScore': 10.17510605321669,
    'calculatedMassToCharge': 911.4144,
    'chargeState': 1,
    'experimentalMassToCharge': 911.413,
    'id': 'SEQ_spec11a_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot2_pep1',
    'rank': 1},
   {'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec11a_pep2'}],
    'ProteinScape:IntensityCoverage': 0.2517734933944088,
    'ProteinScape:SequestMetaScore': 6.005532583410669,
    'calculatedMassToCharge': 1365.722015,
    'chargeState': 1,
    'experimentalMassToCharge': 1365.721,
    'id': 'SEQ_spec11a_pep2',
    'passThreshold': True,
    'peptide_ref': 'prot3_pep1',
    'rank': 2}],
  'id': 'SEQ_spec11a',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=11'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec12_pep1'}],
    'ProteinScape:IntensityCoverage': 0.4884754815768041,
    'ProteinScape:SequestMetaScore': 12.042955809241318,
    'calculatedMassToCharge': 2255.9515,
    'chargeState': 1,
    'experimentalMassToCharge': 2255.95,
    'id': 'SEQ_spec12_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot3_pep2',
    'rank': 1},
   {'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec12_pep2'}],
    'ProteinScape:IntensityCoverage': 0.554279316913958,
    'ProteinScape:SequestMetaScore': 3.1184106313104283,
    'calculatedMassToCharge': 3941.036315,
    'chargeState': 1,
    'experimentalMassToCharge': 3941.081,
    'id': 'SEQ_spec12_pep2',
    'passThreshold': True,
    'peptide_ref': 'prot2_pep2',
    'rank': 2}],
  'id': 'SEQ_spec12',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=12'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec13_pep1'}],
    'ProteinScape:IntensityCoverage': 0.39717937427768873,
    'ProteinScape:SequestMetaScore': 4.159878401845841,
    'calculatedMassToCharge': 911.4144,
    'chargeState': 1,
    'experimentalMassToCharge': 911.415,
    'id': 'SEQ_spec13_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot2_pep1',
    'rank': 1},
   {'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec13_pep2'}],
    'ProteinScape:IntensityCoverage': 0.136423966822031,
    'ProteinScape:SequestMetaScore': 5.725397508852668,
    'calculatedMassToCharge': 2192.932715,
    'chargeState': 1,
    'experimentalMassToCharge': 2192.9,
    'id': 'SEQ_spec13_pep2',
    'passThreshold': True,
    'peptide_ref': 'prot3_pep3',
    'rank': 2}],
  'id': 'SEQ_spec13',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=13'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec15_pep1'}],
    'ProteinScape:IntensityCoverage': 0.2854129700126088,
    'ProteinScape:SequestMetaScore': 6.181682868401155,
    'calculatedMassToCharge': 1469.8071,
    'chargeState': 1,
    'experimentalMassToCharge': 1469.806,
    'id': 'SEQ_spec15_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot4_pep1',
    'rank': 1}],
  'id': 'SEQ_spec15',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=15'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_SEQ_spec20_pep1'}],
    'ProteinScape:IntensityCoverage': 0.29049959198538566,
    'ProteinScape:SequestMetaScore': 6.669916225794168,
    'calculatedMassToCharge': 1225.6059,
    'chargeState': 1,
    'experimentalMassToCharge': 1225.604,
    'id': 'SEQ_spec20_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot4_pep2',
    'rank': 1}],
  'id': 'SEQ_spec20',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=20'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec2b_pep1'}],
    'calculatedMassToCharge': 2035.0745,
    'chargeState': 1,
    'experimentalMassToCharge': 2035.075,
    'id': 'Mas_spec2b_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot5_pep1',
    'rank': 1}],
  'id': 'Mas_spec2b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=2'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec3b_pep1'}],
    'calculatedMassToCharge': 1834.8856,
    'chargeState': 1,
    'experimentalMassToCharge': 1834.884,
    'id': 'Mas_spec3b_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot5_pep2',
    'rank': 1}],
  'id': 'Mas_spec3b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=3'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec4_pep1'}],
    'calculatedMassToCharge': 1097.5049,
    'chargeState': 1,
    'experimentalMassToCharge': 1097.503,
    'id': 'Mas_spec4_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot5_pep3',
    'rank': 1}],
  'id': 'Mas_spec4',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=4'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec6_pep1'}],
    'calculatedMassToCharge': 975.4457,
    'chargeState': 1,
    'experimentalMassToCharge': 975.446,
    'id': 'Mas_spec6_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot6_pep1',
    'rank': 1},
   {'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec6_pep2'}],
    'calculatedMassToCharge': 912.3993,
    'chargeState': 1,
    'experimentalMassToCharge': 912.29,
    'id': 'Mas_spec6_pep2',
    'passThreshold': True,
    'peptide_ref': 'prot7_pep1',
    'rank': 1}],
  'id': 'Mas_spec6',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=6'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec11b_pep1'}],
    'ProteinScape:IntensityCoverage': 0.0,
    'ProteinScape:MascotScore': 33.82,
    'calculatedMassToCharge': 1365.722015,
    'chargeState': 1,
    'experimentalMassToCharge': 1365.721,
    'id': 'Mas_spec11b_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot3_pep1',
    'rank': 1}],
  'id': 'Mas_spec11b',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=11'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec12_pep1'}],
    'ProteinScape:IntensityCoverage': 0.0,
    'ProteinScape:MascotScore': 39.0,
    'calculatedMassToCharge': 2256.9515,
    'chargeState': 1,
    'experimentalMassToCharge': 2256.952,
    'id': 'Mas_spec12_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot3_pep2',
    'rank': 1}],
  'id': 'Mas_spec12',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=12'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec35_pep1'}],
    'calculatedMassToCharge': 2261.0939,
    'chargeState': 1,
    'experimentalMassToCharge': 2261.092,
    'id': 'Mas_spec35_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot6_pep2',
    'rank': 1}],
  'id': 'Mas_spec35',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=35'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec36b1_pep1'}],
    'calculatedMassToCharge': 1115.6168,
    'chargeState': 1,
    'experimentalMassToCharge': 1115.617,
    'id': 'Mas_spec36b1_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot7_pep2',
    'rank': 1}],
  'id': 'Mas_spec36b1',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=36'},
 {'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'peptideEvidence_ref': 'PE1_Mas_spec40_pep1'}],
    'calculatedMassToCharge': 2035.0017,
    'chargeState': 1,
    'experimentalMassToCharge': 2035.002,
    'id': 'Mas_spec40_pep1',
    'passThreshold': True,
    'peptide_ref': 'prot7_pep3',
    'rank': 1}],
  'id': 'Mas_spec40',
  'spectraData_ref': 'LCMALDI_spectra',
  'spectrumID': 'databasekey=40'}],

(True, True): [{'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'AGTQIENIDEDFR',
      'Seq': 'MVDYHAANQSYQYGPSSAGNGAGGGGSMGDYMAQEDDWDRDLLLDPAWEKQQRKTFTAWCNSHLRKAGTQIENIDEDFRDGLKLMLLLEVISGERLPKPERGKMRVHKINNVNKALDFIASKGVKLVSIGAEEIVDGNAKMTLGMIWTIILRFAIQDISVEETSAKEGLLLWCQRKTAPYKNVNVQNFHISWKDGLAFNALIHRHRPELIEYDKLRKDDPVTNLNNAFEVAEKYLDIPKMLDAEDIVNTARPDEKAIMTYVSSFYHAFSGAQKAETAANRICKVLAVNQENEHLMEDYEKLASDLLEWIRRTIPWLEDRVPQKTIQEMQQKLEDFRDYRRVHKPPKVQEKCQLEINFNTLQTKLRLSNRPAFMPSEGKMVSDINNGWQHLEQAEKGYEEWLLNEIRRLERLDHLAEKFRQKASIHEAWTDGKEAMLKHRDYETATLSDIKALIRKHEAFESDLAAHQDRVEQIAAIAQELNELDYYDSHNVNTRCQKICDQWDALGSLTHSRREALEKTEKQLEAIDQLHLEYAKRAAPFNNWMESAMEDLQDMFIVHTIEEIEGLISAHDQFKSTLPDADREREAILAIHKEAQRIAESNHIKLSGSNPYTTVTPQIINSKWEKVQQLVPKRDHALLEEQSKQQSNEHLRRQFASQANVVGPWIQTKMEEIGRISIEMNGTLEDQLSHLKQYERSIVDYKPNLDLLEQQHQLIQEALIFDNKHTNYTMEHIRVGWEQLLTTIARTINEVENQILTRDAKGISQEQMQEFRASFNHFDKDHGGALGPEEFKACLISLGYDVENDRQGEAEFNRIMSLVDPNHSGLVTFQAFIDFMSRETTDTDTADQVIASFKVLAGDKNFITAEELRRELPPDQAEYCIARMAPYQGPDAVPGALDYKSFSTALYGESDL',
      'accession': 'IPI00013808.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 79,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'D',
      'pre': 'K',
      'protein description': 'IPI:IPI00013808.1|SWISS-PROT:O43707|TREMBL:Q96BG6|ENSEMBL:ENSP00000252699|REFSEQ:NP_004915|H-INV:HIT000032172|VEGA:OTTHUMP00000076071;OTTHUMP00000174445 Tax_Id=9606 Gene_Symbol=ACTN4 Alpha-actinin-4',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 67,
      'version': '3.15'}],
    'PeptideSequence': 'AGTQIENIDEDFR',
    'ProteinScape:IntensityCoverage': 0.3919545603809718,
    'ProteinScape:SequestMetaScore': 7.59488518903425,
    'calculatedMassToCharge': 1507.695,
    'chargeState': 1,
    'experimentalMassToCharge': 1507.696,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=1'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'AGTQIENIDEDFRDGLK',
      'Seq': 'MVDYHAANQSYQYGPSSAGNGAGGGGSMGDYMAQEDDWDRDLLLDPAWEKQQRKTFTAWCNSHLRKAGTQIENIDEDFRDGLKLMLLLEVISGERLPKPERGKMRVHKINNVNKALDFIASKGVKLVSIGAEEIVDGNAKMTLGMIWTIILRFAIQDISVEETSAKEGLLLWCQRKTAPYKNVNVQNFHISWKDGLAFNALIHRHRPELIEYDKLRKDDPVTNLNNAFEVAEKYLDIPKMLDAEDIVNTARPDEKAIMTYVSSFYHAFSGAQKAETAANRICKVLAVNQENEHLMEDYEKLASDLLEWIRRTIPWLEDRVPQKTIQEMQQKLEDFRDYRRVHKPPKVQEKCQLEINFNTLQTKLRLSNRPAFMPSEGKMVSDINNGWQHLEQAEKGYEEWLLNEIRRLERLDHLAEKFRQKASIHEAWTDGKEAMLKHRDYETATLSDIKALIRKHEAFESDLAAHQDRVEQIAAIAQELNELDYYDSHNVNTRCQKICDQWDALGSLTHSRREALEKTEKQLEAIDQLHLEYAKRAAPFNNWMESAMEDLQDMFIVHTIEEIEGLISAHDQFKSTLPDADREREAILAIHKEAQRIAESNHIKLSGSNPYTTVTPQIINSKWEKVQQLVPKRDHALLEEQSKQQSNEHLRRQFASQANVVGPWIQTKMEEIGRISIEMNGTLEDQLSHLKQYERSIVDYKPNLDLLEQQHQLIQEALIFDNKHTNYTMEHIRVGWEQLLTTIARTINEVENQILTRDAKGISQEQMQEFRASFNHFDKDHGGALGPEEFKACLISLGYDVENDRQGEAEFNRIMSLVDPNHSGLVTFQAFIDFMSRETTDTDTADQVIASFKVLAGDKNFITAEELRRELPPDQAEYCIARMAPYQGPDAVPGALDYKSFSTALYGESDL',
      'accession': 'IPI00013808.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 83,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'L',
      'pre': 'K',
      'protein description': 'IPI:IPI00013808.1|SWISS-PROT:O43707|TREMBL:Q96BG6|ENSEMBL:ENSP00000252699|REFSEQ:NP_004915|H-INV:HIT000032172|VEGA:OTTHUMP00000076071;OTTHUMP00000174445 Tax_Id=9606 Gene_Symbol=ACTN4 Alpha-actinin-4',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 67,
      'version': '3.15'}],
    'PeptideSequence': 'AGTQIENIDEDFRDGLK',
    'ProteinScape:IntensityCoverage': 0.5070386909133888,
    'ProteinScape:SequestMetaScore': 10.8810331335713,
    'calculatedMassToCharge': 1920.9224,
    'chargeState': 1,
    'experimentalMassToCharge': 1920.923,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=2'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'ALDFIASK',
      'Seq': 'MVDYHAANQSYQYGPSSAGNGAGGGGSMGDYMAQEDDWDRDLLLDPAWEKQQRKTFTAWCNSHLRKAGTQIENIDEDFRDGLKLMLLLEVISGERLPKPERGKMRVHKINNVNKALDFIASKGVKLVSIGAEEIVDGNAKMTLGMIWTIILRFAIQDISVEETSAKEGLLLWCQRKTAPYKNVNVQNFHISWKDGLAFNALIHRHRPELIEYDKLRKDDPVTNLNNAFEVAEKYLDIPKMLDAEDIVNTARPDEKAIMTYVSSFYHAFSGAQKAETAANRICKVLAVNQENEHLMEDYEKLASDLLEWIRRTIPWLEDRVPQKTIQEMQQKLEDFRDYRRVHKPPKVQEKCQLEINFNTLQTKLRLSNRPAFMPSEGKMVSDINNGWQHLEQAEKGYEEWLLNEIRRLERLDHLAEKFRQKASIHEAWTDGKEAMLKHRDYETATLSDIKALIRKHEAFESDLAAHQDRVEQIAAIAQELNELDYYDSHNVNTRCQKICDQWDALGSLTHSRREALEKTEKQLEAIDQLHLEYAKRAAPFNNWMESAMEDLQDMFIVHTIEEIEGLISAHDQFKSTLPDADREREAILAIHKEAQRIAESNHIKLSGSNPYTTVTPQIINSKWEKVQQLVPKRDHALLEEQSKQQSNEHLRRQFASQANVVGPWIQTKMEEIGRISIEMNGTLEDQLSHLKQYERSIVDYKPNLDLLEQQHQLIQEALIFDNKHTNYTMEHIRVGWEQLLTTIARTINEVENQILTRDAKGISQEQMQEFRASFNHFDKDHGGALGPEEFKACLISLGYDVENDRQGEAEFNRIMSLVDPNHSGLVTFQAFIDFMSRETTDTDTADQVIASFKVLAGDKNFITAEELRRELPPDQAEYCIARMAPYQGPDAVPGALDYKSFSTALYGESDL',
      'accession': 'IPI00013808.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 122,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'G',
      'pre': 'K',
      'protein description': 'IPI:IPI00013808.1|SWISS-PROT:O43707|TREMBL:Q96BG6|ENSEMBL:ENSP00000252699|REFSEQ:NP_004915|H-INV:HIT000032172|VEGA:OTTHUMP00000076071;OTTHUMP00000174445 Tax_Id=9606 Gene_Symbol=ACTN4 Alpha-actinin-4',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 115,
      'version': '3.15'}],
    'PeptideSequence': 'ALDFIASK',
    'ProteinScape:IntensityCoverage': 0.43376827663349576,
    'ProteinScape:SequestMetaScore': 6.1021771936508955,
    'calculatedMassToCharge': 864.4752,
    'chargeState': 1,
    'experimentalMassToCharge': 864.474,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=3'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'Modification': [{'location': 1,
      'name': 'Oxidation'}],
    'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'Modification': [{'location': 1, 'name': 'Oxidation'}],
      'PeptideSequence': 'MLDAEDIVNTARPDEK',
      'Seq': 'MVDYHAANQSYQYGPSSAGNGAGGGGSMGDYMAQEDDWDRDLLLDPAWEKQQRKTFTAWCNSHLRKAGTQIENIDEDFRDGLKLMLLLEVISGERLPKPERGKMRVHKINNVNKALDFIASKGVKLVSIGAEEIVDGNAKMTLGMIWTIILRFAIQDISVEETSAKEGLLLWCQRKTAPYKNVNVQNFHISWKDGLAFNALIHRHRPELIEYDKLRKDDPVTNLNNAFEVAEKYLDIPKMLDAEDIVNTARPDEKAIMTYVSSFYHAFSGAQKAETAANRICKVLAVNQENEHLMEDYEKLASDLLEWIRRTIPWLEDRVPQKTIQEMQQKLEDFRDYRRVHKPPKVQEKCQLEINFNTLQTKLRLSNRPAFMPSEGKMVSDINNGWQHLEQAEKGYEEWLLNEIRRLERLDHLAEKFRQKASIHEAWTDGKEAMLKHRDYETATLSDIKALIRKHEAFESDLAAHQDRVEQIAAIAQELNELDYYDSHNVNTRCQKICDQWDALGSLTHSRREALEKTEKQLEAIDQLHLEYAKRAAPFNNWMESAMEDLQDMFIVHTIEEIEGLISAHDQFKSTLPDADREREAILAIHKEAQRIAESNHIKLSGSNPYTTVTPQIINSKWEKVQQLVPKRDHALLEEQSKQQSNEHLRRQFASQANVVGPWIQTKMEEIGRISIEMNGTLEDQLSHLKQYERSIVDYKPNLDLLEQQHQLIQEALIFDNKHTNYTMEHIRVGWEQLLTTIARTINEVENQILTRDAKGISQEQMQEFRASFNHFDKDHGGALGPEEFKACLISLGYDVENDRQGEAEFNRIMSLVDPNHSGLVTFQAFIDFMSRETTDTDTADQVIASFKVLAGDKNFITAEELRRELPPDQAEYCIARMAPYQGPDAVPGALDYKSFSTALYGESDL',
      'accession': 'IPI00013808.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 255,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'A',
      'pre': 'K',
      'protein description': 'IPI:IPI00013808.1|SWISS-PROT:O43707|TREMBL:Q96BG6|ENSEMBL:ENSP00000252699|REFSEQ:NP_004915|H-INV:HIT000032172|VEGA:OTTHUMP00000076071;OTTHUMP00000174445 Tax_Id=9606 Gene_Symbol=ACTN4 Alpha-actinin-4',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 240,
      'version': '3.15'}],
    'PeptideSequence': 'MLDAEDIVNTARPDEK',
    'ProteinScape:IntensityCoverage': 0.16164593872706742,
    'ProteinScape:SequestMetaScore': 5.635013787097159,
    'calculatedMassToCharge': 1832.862115,
    'chargeState': 1,
    'experimentalMassToCharge': 1832.863,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=10'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'SYTSGPGSR',
      'Seq': 'SIRVTQKSYKVSTSGPRAFSSRSYTSGPGSRISSSSFSRVGSSNFRGGLGGGYGGASGMGGITAVTVNQSLLSPLVLEVDPNIQAVRTQEKEQIKTLNNKFASFIDKVRFLEQQNKMLETKWSLLQQQKTARSNMDNMFESYINNLRRQLETLGQEKLKLEAELGNMQGLVEDFKNKYEDEINKRTEMENEFVLIKKDVDEAYMNKVELESRLEGLTDEINFLRQLYEEEIRELQSQISDTSVVLSMDNSRSLDMDSIIAEVKAQYEDIANRSRAEAESMYQIKYEELQSLAGKHGDDLRRTKTEISEMNRNISRLQAEIEGLKGQRASLEAAIADAEQRGELAIKDANAKLSELEAALQRAKQDMARQLREYQELMNVKLALDIEIATYRKLLEGEESRLESGMQNMSIHTKTTGGYAGGLSSAYGGLTSPGLSYSLGSSFGSGAGSSSFSRTSSSRAVVVKKIETRDGKLVSESSDVLPK',
      'accession': 'IPI00554648.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 31,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'I',
      'pre': 'R',
      'protein description': '>IPI:IPI00554648.1|SWISS-PROT:P05787 Tax_Id=9606 Keratin, type II cytoskeletal 8',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 23,
      'version': '3.15'}],
    'PeptideSequence': 'SYTSGPGSR',
    'ProteinScape:IntensityCoverage': 0.6146634530945828,
    'ProteinScape:SequestMetaScore': 10.17510605321669,
    'calculatedMassToCharge': 911.4144,
    'chargeState': 1,
    'experimentalMassToCharge': 911.413,
    'passThreshold': True,
    'rank': 1},
   {'Modification': [{'location': 11, 'name': 'Oxidation'}],
    'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'Modification': [{'location': 11, 'name': 'Oxidation'}],
      'PeptideSequence': 'TLTLVDTGIGMTK',
      'Seq': 'PEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYESLTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEALQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEPIGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEEEKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWTRNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKKKKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRKNIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGDEMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCVQQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTISNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETLRQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVAAEEPNAAVPDEIPPLEGDEDASRMEEVD',
      'accession': 'IPI00414676.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 94,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'A',
      'pre': 'R',
      'protein description': '>IPI:IPI00414676.5|SWISS-PROT:P08238|TREMBL:Q5T9W7;Q6PK50;Q9H6X9|ENSEMBL:ENSP00000325875|REFSEQ:NP_031381|H-INV:HIT000008644;HIT000032091;HIT000034201;HIT000035963;HIT000036733;HIT000049765;HIT000057726|VEGA:OTTHUMP00000016517;OTTHUMP00000016518;OTTHUMP00000016519 Tax_Id=9606 Heat shock protein HSP 90-beta',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 82,
      'version': '3.15'}],
    'PeptideSequence': 'TLTLVDTGIGMTK',
    'ProteinScape:IntensityCoverage': 0.2517734933944088,
    'ProteinScape:SequestMetaScore': 6.005532583410669,
    'calculatedMassToCharge': 1365.722015,
    'chargeState': 1,
    'experimentalMassToCharge': 1365.721,
    'passThreshold': True,
    'rank': 2}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=11'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'HNDDEQYAWESSAGGSFTVR',
      'Seq': 'PEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYESLTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEALQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEPIGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEEEKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWTRNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKKKKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRKNIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGDEMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCVQQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTISNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETLRQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVAAEEPNAAVPDEIPPLEGDEDASRMEEVD',
      'accession': 'IPI00414676.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 167,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'A',
      'pre': 'K',
      'protein description': '>IPI:IPI00414676.5|SWISS-PROT:P08238|TREMBL:Q5T9W7;Q6PK50;Q9H6X9|ENSEMBL:ENSP00000325875|REFSEQ:NP_031381|H-INV:HIT000008644;HIT000032091;HIT000034201;HIT000035963;HIT000036733;HIT000049765;HIT000057726|VEGA:OTTHUMP00000016517;OTTHUMP00000016518;OTTHUMP00000016519 Tax_Id=9606 Heat shock protein HSP 90-beta',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 148,
      'version': '3.15'}],
    'PeptideSequence': 'HNDDEQYAWESSAGGSFTVR',
    'ProteinScape:IntensityCoverage': 0.4884754815768041,
    'ProteinScape:SequestMetaScore': 12.042955809241318,
    'calculatedMassToCharge': 2255.9515,
    'chargeState': 1,
    'experimentalMassToCharge': 2255.95,
    'passThreshold': True,
    'rank': 1},
   {'Modification': [{'location': 13, 'name': 'Oxidation'}],
    'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'Modification': [{'location': 13, 'name': 'Oxidation'}],
      'PeptideSequence': 'GGLGGGYGGASGMGGITAVTVNQSLLSPLVLEVDPNIQAVR',
      'Seq': 'SIRVTQKSYKVSTSGPRAFSSRSYTSGPGSRISSSSFSRVGSSNFRGGLGGGYGGASGMGGITAVTVNQSLLSPLVLEVDPNIQAVRTQEKEQIKTLNNKFASFIDKVRFLEQQNKMLETKWSLLQQQKTARSNMDNMFESYINNLRRQLETLGQEKLKLEAELGNMQGLVEDFKNKYEDEINKRTEMENEFVLIKKDVDEAYMNKVELESRLEGLTDEINFLRQLYEEEIRELQSQISDTSVVLSMDNSRSLDMDSIIAEVKAQYEDIANRSRAEAESMYQIKYEELQSLAGKHGDDLRRTKTEISEMNRNISRLQAEIEGLKGQRASLEAAIADAEQRGELAIKDANAKLSELEAALQRAKQDMARQLREYQELMNVKLALDIEIATYRKLLEGEESRLESGMQNMSIHTKTTGGYAGGLSSAYGGLTSPGLSYSLGSSFGSGAGSSSFSRTSSSRAVVVKKIETRDGKLVSESSDVLPK',
      'accession': 'IPI00554648.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 87,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'T',
      'pre': 'R',
      'protein description': '>IPI:IPI00554648.1|SWISS-PROT:P05787 Tax_Id=9606 Keratin, type II cytoskeletal 8',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 47,
      'version': '3.15'}],
    'PeptideSequence': 'GGLGGGYGGASGMGGITAVTVNQSLLSPLVLEVDPNIQAVR',
    'ProteinScape:IntensityCoverage': 0.554279316913958,
    'ProteinScape:SequestMetaScore': 3.1184106313104283,
    'calculatedMassToCharge': 3941.036315,
    'chargeState': 1,
    'experimentalMassToCharge': 3941.081,
    'passThreshold': True,
    'rank': 2}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=12'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'SYTSGPGSR',
      'Seq': 'SIRVTQKSYKVSTSGPRAFSSRSYTSGPGSRISSSSFSRVGSSNFRGGLGGGYGGASGMGGITAVTVNQSLLSPLVLEVDPNIQAVRTQEKEQIKTLNNKFASFIDKVRFLEQQNKMLETKWSLLQQQKTARSNMDNMFESYINNLRRQLETLGQEKLKLEAELGNMQGLVEDFKNKYEDEINKRTEMENEFVLIKKDVDEAYMNKVELESRLEGLTDEINFLRQLYEEEIRELQSQISDTSVVLSMDNSRSLDMDSIIAEVKAQYEDIANRSRAEAESMYQIKYEELQSLAGKHGDDLRRTKTEISEMNRNISRLQAEIEGLKGQRASLEAAIADAEQRGELAIKDANAKLSELEAALQRAKQDMARQLREYQELMNVKLALDIEIATYRKLLEGEESRLESGMQNMSIHTKTTGGYAGGLSSAYGGLTSPGLSYSLGSSFGSGAGSSSFSRTSSSRAVVVKKIETRDGKLVSESSDVLPK',
      'accession': 'IPI00554648.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 31,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'I',
      'pre': 'R',
      'protein description': '>IPI:IPI00554648.1|SWISS-PROT:P05787 Tax_Id=9606 Keratin, type II cytoskeletal 8',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 23,
      'version': '3.15'}],
    'PeptideSequence': 'SYTSGPGSR',
    'ProteinScape:IntensityCoverage': 0.39717937427768873,
    'ProteinScape:SequestMetaScore': 4.159878401845841,
    'calculatedMassToCharge': 911.4144,
    'chargeState': 1,
    'experimentalMassToCharge': 911.415,
    'passThreshold': True,
    'rank': 1},
   {'Modification': [{'location': 10, 'name': 'Oxidation'}],
    'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'Modification': [{'location': 10, 'name': 'Oxidation'}],
      'PeptideSequence': 'YHTSQSGDEMTSLSEYVSR',
      'Seq': 'PEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYESLTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEALQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEPIGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEEEKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWTRNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKKKKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRKNIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGDEMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCVQQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTISNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETLRQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVAAEEPNAAVPDEIPPLEGDEDASRMEEVD',
      'accession': 'IPI00414676.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 474,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'M',
      'pre': 'R',
      'protein description': '>IPI:IPI00414676.5|SWISS-PROT:P08238|TREMBL:Q5T9W7;Q6PK50;Q9H6X9|ENSEMBL:ENSP00000325875|REFSEQ:NP_031381|H-INV:HIT000008644;HIT000032091;HIT000034201;HIT000035963;HIT000036733;HIT000049765;HIT000057726|VEGA:OTTHUMP00000016517;OTTHUMP00000016518;OTTHUMP00000016519 Tax_Id=9606 Heat shock protein HSP 90-beta',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 456,
      'version': '3.15'}],
    'PeptideSequence': 'YHTSQSGDEMTSLSEYVSR',
    'ProteinScape:IntensityCoverage': 0.136423966822031,
    'ProteinScape:SequestMetaScore': 5.725397508852668,
    'calculatedMassToCharge': 2192.932715,
    'chargeState': 1,
    'experimentalMassToCharge': 2192.9,
    'passThreshold': True,
    'rank': 2}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=13'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'ENDILKMPIAAVR',
      'Seq': 'YQQKTRHDAFPRIQLALRAGAKSKEDLFSEPKLYEDKEQRISSELPEEALDDSSPSDTSLIAVEREISSNLRHSSTNYEEHLRKLKKDKYSEAVDPSGKPLGLLVILGNQYMREDEIATEERMPENKSTDISTYIKEFDGKEIAFPTENSYFPARGDKSKAVTAKWKRFTPFPLQTDDNSAAKLTEVFKIQLTTVGKLGKCSEGGENKEDKCTDNLCLNPPDELTEHREAPVTDTKPIMPEQIIITTKEISDSQLENRDETAPIALDLIALVSVNSLTGETNRKMEEYKSKKRRTTRLEETGFHILHNREVNMDNGECVFPIHYDAAQEMQPHTDSSKVMKASEFQKDIILMELIEKFDHNVKLLSKDCVEVQNSMANLELDKESEEQAVGDGSCLTRGTLVIKAQNGKNTGENDSTKETREYLRKKMDEAEDYGLVLKDDTYIEVWDVAVQITYLLKRSIEWPESECIDIEPFVHKAKSYINVEKETESHKLVQHKYKCRPLFRGENKDVTKRLLYGKILLEDKLSSASGLKSTELWDLDEDYEVTWRQEILLNKNKKVAPDEKETYIVLQNNLYPMQPVVMPSIPARMMSLENDILKMPIAAVRVKVVDITINKFLMGEINADDMEFPTSGFLEQHSDFGGLANGESQNDKPTEGQAREIEPIAKEEYVIDLEWGLRITQPTSEYGYDGELVVYVTKGMGKQTEPESLSYVCVVEGFAKAQLPERQITGKEDSGFIRRQQRLLEDDFSMKKKIFEGLDPILSEKKLDMQFRKFSMKWQYLKDILPADFDKEKEIFREFHKIEIKVSFGHKGMESKAALYIKFYETFERELKQFLSAEPRYRDDACEGLQLEV',
      'accession': 'SHD00382470.3',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 191,
      'isDecoy': True,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'V',
      'pre': 'L',
      'protein description': '>SHD:SHD00382470.3|SWISS-PROT:P07900-2|TREMBL:Q86SX1|ENSEMBL:ENSP00000335153|REFSEQ:NP_001017963|VEGA:OTTHUMP00000041671 Tax_Id=9606 Gene_Symbol=HSP90AA1 heat shock protein 90kDa alpha (cytosolic), class A member 1 isoform 1',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 183,
      'version': '3.15'}],
    'PeptideSequence': 'ENDILKMPIAAVR',
    'ProteinScape:IntensityCoverage': 0.2854129700126088,
    'ProteinScape:SequestMetaScore': 6.181682868401155,
    'calculatedMassToCharge': 1469.8071,
    'chargeState': 1,
    'experimentalMassToCharge': 1469.806,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=15'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'LLEDDFSMKK',
      'Seq': 'YQQKTRHDAFPRIQLALRAGAKSKEDLFSEPKLYEDKEQRISSELPEEALDDSSPSDTSLIAVEREISSNLRHSSTNYEEHLRKLKKDKYSEAVDPSGKPLGLLVILGNQYMREDEIATEERMPENKSTDISTYIKEFDGKEIAFPTENSYFPARGDKSKAVTAKWKRFTPFPLQTDDNSAAKLTEVFKIQLTTVGKLGKCSEGGENKEDKCTDNLCLNPPDELTEHREAPVTDTKPIMPEQIIITTKEISDSQLENRDETAPIALDLIALVSVNSLTGETNRKMEEYKSKKRRTTRLEETGFHILHNREVNMDNGECVFPIHYDAAQEMQPHTDSSKVMKASEFQKDIILMELIEKFDHNVKLLSKDCVEVQNSMANLELDKESEEQAVGDGSCLTRGTLVIKAQNGKNTGENDSTKETREYLRKKMDEAEDYGLVLKDDTYIEVWDVAVQITYLLKRSIEWPESECIDIEPFVHKAKSYINVEKETESHKLVQHKYKCRPLFRGENKDVTKRLLYGKILLEDKLSSASGLKSTELWDLDEDYEVTWRQEILLNKNKKVAPDEKETYIVLQNNLYPMQPVVMPSIPARMMSLENDILKMPIAAVRVKVVDITINKFLMGEINADDMEFPTSGFLEQHSDFGGLANGESQNDKPTEGQAREIEPIAKEEYVIDLEWGLRITQPTSEYGYDGELVVYVTKGMGKQTEPESLSYVCVVEGFAKAQLPERQITGKEDSGFIRRQQRLLEDDFSMKKKIFEGLDPILSEKKLDMQFRKFSMKWQYLKDILPADFDKEKEIFREFHKIEIKVSFGHKGMESKAALYIKFYETFERELKQFLSAEPRYRDDACEGLQLEV',
      'accession': 'SHD00382470.3',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 234,
      'isDecoy': True,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'K',
      'pre': 'R',
      'protein description': '>SHD:SHD00382470.3|SWISS-PROT:P07900-2|TREMBL:Q86SX1|ENSEMBL:ENSP00000335153|REFSEQ:NP_001017963|VEGA:OTTHUMP00000041671 Tax_Id=9606 Gene_Symbol=HSP90AA1 heat shock protein 90kDa alpha (cytosolic), class A member 1 isoform 1',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 223,
      'version': '3.15'}],
    'PeptideSequence': 'LLEDDFSMKK',
    'ProteinScape:IntensityCoverage': 0.29049959198538566,
    'ProteinScape:SequestMetaScore': 6.669916225794168,
    'calculatedMassToCharge': 1225.6059,
    'chargeState': 1,
    'experimentalMassToCharge': 1225.604,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=20'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'DGHNLISLLEVLSGDSLPR',
      'Seq': 'MKIVPDERDRVQKKTFTKWVNKHLIKAQRHISDLYEDLRDGHNLISLLEVLSGDSLPREKGRMRFHKLQNVQIALDYLRHRQVKLVNIRNDDIADGNPKLTLGLIWTIILHFQISDIQVSGQSEDMTAKEKLLLWSQRMVEGYQGLRCDNFTSSWRDGRLFNAIIHRHKPLLIDMNKVYRQTNLENLDQAFSVAERDLGVTRLLDPEDVDVPQPDEKSIITYVSSLYDAMPRVPDVQDGVRANELQLRWQEYRELVLLLLQWMRHHTAAFEERRFPSSFEEIEILWSQFLKFKEMELPAKEADKNRSKGIYQSLEGAVQAGQLKVPPGYHPLDVEKEWGKLHVAILEREKQLRSEFERLECLQRIVTKLQMEAGLCEEQLNQADALLQSDVRLLAAGKVPQRAGEVERDLDKADSMIRLLFNDVQTLKDGRHPQGEQMYRRVYRLHERLVAIRTEYNLRLKAGVAAPATQVAQVTLQSVQRRPELEDSTLRYLQDLLAWVEENQHRVDGAEWGVDLPSVEAQLGSHRGLHQSIEEFRAKIERARSDEGQLSPATRGAYRDCLGRLDLQYAKLLNSSKARLRSLESLHSFVAAATKELMWLNEKEEEEVGFDWSDRNTNMTAKKESYSALMRELELKEKKIKELQNAGDRLLREDHPARPTVESFQAALQTQWSWMLQLCCCIEAHLKENAAYFQFFSDVREAEGQLQKLQEALRRKYSCDRSATVTRLEDLLQDAQDEKEQLNEYKGHLSGLAKRAKAVVQLKPRHPAHPMRGRLPLLAVCDYKQVEVTVHKGDECQLVGPAQPSHWKVLSSSGSEAAVPSVCFLVPPPNQEAQEAVTRLEAQHQALVTLWHQLHVDMKSLLAWQSLRRDVQLIRSWSLATFRTLKPEEQRQALHSLELHYQAFLRDSQDAGGFGPEDRLMAEREYGSCSHHYQQLLQSLEQGAQEESRCQRCISELKDIRLQLEACETRTVHRLRLPLDKEPARECAQRIAEQQKAQAEVEGLGKGVARLSAEAEKVLALPEPSPAAPTLRSELELTLGKLEQVRSLSAIYLEKLKTISLVIRGTQGAEEVLRAHEEQLKEAQAVPATLPELEATKASLKKLRAQAEAQQPTFDALRDELRGAQEVGERLQQRHGERDVEVERWRERVAQLLERWQAVLAQTDVRQRELEQLGRQLRYYRESADPLGAWLQDARRRQEQIQAMPLADSQAVREQLRQEQALLEEIERHGEKVEECQRFAKQYINAIKDYELQLVTYKAQLEPVASPAKKPKVQSGSESVIQEYVDLRTHYSELTTLTSQYIKFISETLRRMEEEERLAEQQRAEERERLAEVEAALEKQRQLAEAHAQAKAQAEREAKELQQRMQEEVVRREEAAVDAQQQKRSIQEELQQLRQSSEAEIQAKARQAEAAERSRLRIEEEIRVVRLQLEATERQRGGAEGELQALRARAEEAEAQKRQAQEEAERLRRQVQDESQRKRQAEVELASRVKAEAEAAREKQRALQALEELRLQAEEAERRLRQAEVERARQVQVALETAQRSAEAELQSKRASFAEKTAQLERSLQEEHVAVAQLREEAERRAQQQAEAERAREEAERELERWQLKANEALRLRLQAEEVAQQKSLAQAEAEKQKEEAEREARRRGKAEEQAVRQRELAEQELEKQRQLAEGTAQQRLAAEQELIRLRAETEQGEQQRQLLEEELARLQREAAAATQKRQELEAELAKVRAEMEVLLASKARAEEESRSTSEKSKQRLEAEAGRFRELAEEAARLRALAEEAKRQRQLAEEDAARQRAEAERVLAEKLAAIGEATRLKTEAEIALKEKEAENERLRRLAEDEAFQRRRLEEQAAQHKADIEERLAQLRKASDSELERQKGLVEDTLRQRRQVEEEILALKASFEKAAAGKAELELELGRIRSNAEDTLRSKEQAELEAARQRQLAAEEERRRREAEERVQKSLAAEEEAARQRKAALEEVERLKAKVEEARRLRERAEQESARQLQLAQEAAQKRLQAEEKAHAFAVQQKEQELQQTLQQEQSVLDQLRGEAEAARRAAEEAEEARVQAEREAAQSRRQVEEAERLKQSAEEQAQARAQAQAAAEKLRKEAEQEAARRAQAEQAALRQKQAADAEMEKHKKFAEQTLRQKAQVEQELTTLRLQLEETDHQKNLLDEELQRLKAEATEAARQRSQVEEELFSVRVQMEELSKLKARIEAENRALILRDKDNTQRFLQEEAEKMKQVAEEAARLSVAAQEAARLRQLAEEDLAQQRALAEKMLKEKMQAVQEATRLKAEAELLQQQKELAQEQARRLQEDKEQMAQQLAEETQGFQRTLEAERQRQLEMSAEAERLKLRVAEMSRAQARAEEDAQRFRKQAEEIGEKLHRTELATQEKVTLVQTLEIQRQQSDHDAERLREAIAELEREKEKLQQEAKLLQLKSEEMQTVQQEQLLQETQALQQSFLSEKDSLLQRERFIEQEKAKLEQLFQDEVAKAQQLREEQQRQQQQMEQERQRLVASMEEARRRQHEAEEGVRRKQEELQQLEQQRRQQEELLAEENQRLREQLQLLEEQHRAALAHSEEVTASQVAATKTLPNGRDALDGPAAEAEPEHSFDGLRRKVSAQRLQEAGILSAEELQRLAQGHTTVDELARREDVRHYLQGRSSIAGLLLKATNEKLSVYAALQRQLLSPGTALILLEAQAASGFLLDPVRNRRLTVNEAVKEGVVGPELHHKLLSAERAVTGYKDPYTGQQISLFQAMQKGLIVREHGIRLLEAQIATGGVIDPVHSHRVPVDVAYRRGYFDEEMNRVLADPSDDTKGFFDPNTHENLTYLQLLERCVEDPETGLCLLPLTDKAAKGGELVYTDSEARDVFEKATVSAPFGKFQGKTVTIWEIINSEYFTAEQRRDLLRQFRTGRITVEKIIKIIITVVEEQEQKGRLCFEGLRSLVPAAELLESRVIDRELYQQLQRGERSVRDVAEVDTVRRALRGANVIAGVWLEEAGQKLSIYNALKKDLLPSDMAVALLEAQAGTGHIIDPATSARLTVDEAVRAGLVGPEFHEKLLSAEKAVTGYRDPYTGQSVSLFQALKKGLIPREQGLRLLDAQLSTGGIVDPSKSHRVPLDVACARGCLDEETSRALSAPRADAKAYSDPSTGEPATYGELQQRCRPDQLTGLSLLPLSEKAARARQEELYSELQARETFEKTPVEVPVGGFKGRTVTVWELISSEYFTAEQRQELLRQFRTGKVTVEKVIKILITIVEEVETLRQERLSFSGLRAPVPASELLASGVLSRAQFEQLKDGKTTVKDLSELGSVRTLLQGSGCLAGIYLEDTKEKVSIYEAMRRGLLRATTAALLLEAQAATGFLVDPVRNQRLYVHEAVKAGVVGPELHEQLLSAEKAVTGYRDPYSGSTISLFQAMQKGLVLRQHGIRLLEAQIATGGIIDPVHSHRVPVDVAYQRGYFSEEMNRVLADPSDDTKGFFDPNTHENLTYRQLLERCVEDPETGLRLLPLKGAEKAEVVETTQVYTEEETRRAFEETQIDIPGGGSHGGSTMSLWEVMQSDLIPEEQRAQLMADFQAGRVTKERMIIIIIEIIEKTEIIRQQGLASYDYVRRRLTAEDLFEARIISLETYNLLREGTRSLREALEAESAWCYLYGTGSVAGVYLPGSRQTLSIYQALKKGLLSAEVARLLLEAQAATGFLLDPVKGERLTVDEAVRKGLVGPELHDRLLSAERAVTGYRDPYTEQTISLFQAMKKELIPTEEALRLLDAQLATGGIVDPRLGFHLPLEVAYQRGYLNKDTHDQLSEPSEVRSYVDPSTDERLSYTQLLRRCRRDDGTGQLLLPLSDARKLTFRGLRKQITMEELVRSQVMDEATALQLREGLTSIEEVTKNLQKFLEGTSCIAGVFVDATKERLSVYQAMKKGIIRPGTAFELLEAQAATGYVIDPIKGLKLTVEEAVRMGIVGPEFKDKLLSAERAVTGYKDPYSGKLISLFQAMKKGLILKDHGIRLLEAQIATGGIIDPEESHRLPVEVAYKRGLFDEEMNEILTDPSDDTKGFFDPNTEENLTYLQLMERCITDPQTGLCLLPLKEKKRERKTSSKSSVRKRRVVIVDPETGKEMSVYEAYRKGLIDHQTYLELSEQECEWEEITISSSDGVVKSMIIDRRSGRQYDIDDAIAKNLIDRSALDQYRAGTLSITEFADMLSGNAGGFRSRSSSVGSSSSYPISPAVSRTQLASWSDPTEETGPVAGILDTETLEKVSITEAMHRNLVDNITGQRLLEAQACTGGIIDPSTGERFPVTDAVNKGLVDKIMVDRINLAQKAFCGFEDPRTKTKMSAAQALKKGWLYYEAGQRFLEVQYLTGGLIEPDTPGRVPLDEALQRGTVDARTAQKLRDVGAYSKYLTCPKTKLKISYKDALDRSMVEEGTGLRLLEAAAQSTKGYYSPYSVSGSGSTAGSRTGSRTGSRAGSRRGSFDATGSGFSMTFSSSSYSSSGYGRRYASGSSASLGGPESAVA',
      'accession': 'IPI00398776.3',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 59,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'E',
      'pre': 'R',
      'protein description': '>IPI:IPI00398776.3|TREMBL:Q6S379;Q96IE3|REFSEQ:NP_958783 Tax_Id=9606 plectin 1 isoform 7',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 40,
      'version': '3.15'}],
    'PeptideSequence': 'DGHNLISLLEVLSGDSLPR',
    'calculatedMassToCharge': 2035.0745,
    'chargeState': 1,
    'experimentalMassToCharge': 2035.075,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=2'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'QTNLENLDQAFSVAER',
      'Seq': 'MKIVPDERDRVQKKTFTKWVNKHLIKAQRHISDLYEDLRDGHNLISLLEVLSGDSLPREKGRMRFHKLQNVQIALDYLRHRQVKLVNIRNDDIADGNPKLTLGLIWTIILHFQISDIQVSGQSEDMTAKEKLLLWSQRMVEGYQGLRCDNFTSSWRDGRLFNAIIHRHKPLLIDMNKVYRQTNLENLDQAFSVAERDLGVTRLLDPEDVDVPQPDEKSIITYVSSLYDAMPRVPDVQDGVRANELQLRWQEYRELVLLLLQWMRHHTAAFEERRFPSSFEEIEILWSQFLKFKEMELPAKEADKNRSKGIYQSLEGAVQAGQLKVPPGYHPLDVEKEWGKLHVAILEREKQLRSEFERLECLQRIVTKLQMEAGLCEEQLNQADALLQSDVRLLAAGKVPQRAGEVERDLDKADSMIRLLFNDVQTLKDGRHPQGEQMYRRVYRLHERLVAIRTEYNLRLKAGVAAPATQVAQVTLQSVQRRPELEDSTLRYLQDLLAWVEENQHRVDGAEWGVDLPSVEAQLGSHRGLHQSIEEFRAKIERARSDEGQLSPATRGAYRDCLGRLDLQYAKLLNSSKARLRSLESLHSFVAAATKELMWLNEKEEEEVGFDWSDRNTNMTAKKESYSALMRELELKEKKIKELQNAGDRLLREDHPARPTVESFQAALQTQWSWMLQLCCCIEAHLKENAAYFQFFSDVREAEGQLQKLQEALRRKYSCDRSATVTRLEDLLQDAQDEKEQLNEYKGHLSGLAKRAKAVVQLKPRHPAHPMRGRLPLLAVCDYKQVEVTVHKGDECQLVGPAQPSHWKVLSSSGSEAAVPSVCFLVPPPNQEAQEAVTRLEAQHQALVTLWHQLHVDMKSLLAWQSLRRDVQLIRSWSLATFRTLKPEEQRQALHSLELHYQAFLRDSQDAGGFGPEDRLMAEREYGSCSHHYQQLLQSLEQGAQEESRCQRCISELKDIRLQLEACETRTVHRLRLPLDKEPARECAQRIAEQQKAQAEVEGLGKGVARLSAEAEKVLALPEPSPAAPTLRSELELTLGKLEQVRSLSAIYLEKLKTISLVIRGTQGAEEVLRAHEEQLKEAQAVPATLPELEATKASLKKLRAQAEAQQPTFDALRDELRGAQEVGERLQQRHGERDVEVERWRERVAQLLERWQAVLAQTDVRQRELEQLGRQLRYYRESADPLGAWLQDARRRQEQIQAMPLADSQAVREQLRQEQALLEEIERHGEKVEECQRFAKQYINAIKDYELQLVTYKAQLEPVASPAKKPKVQSGSESVIQEYVDLRTHYSELTTLTSQYIKFISETLRRMEEEERLAEQQRAEERERLAEVEAALEKQRQLAEAHAQAKAQAEREAKELQQRMQEEVVRREEAAVDAQQQKRSIQEELQQLRQSSEAEIQAKARQAEAAERSRLRIEEEIRVVRLQLEATERQRGGAEGELQALRARAEEAEAQKRQAQEEAERLRRQVQDESQRKRQAEVELASRVKAEAEAAREKQRALQALEELRLQAEEAERRLRQAEVERARQVQVALETAQRSAEAELQSKRASFAEKTAQLERSLQEEHVAVAQLREEAERRAQQQAEAERAREEAERELERWQLKANEALRLRLQAEEVAQQKSLAQAEAEKQKEEAEREARRRGKAEEQAVRQRELAEQELEKQRQLAEGTAQQRLAAEQELIRLRAETEQGEQQRQLLEEELARLQREAAAATQKRQELEAELAKVRAEMEVLLASKARAEEESRSTSEKSKQRLEAEAGRFRELAEEAARLRALAEEAKRQRQLAEEDAARQRAEAERVLAEKLAAIGEATRLKTEAEIALKEKEAENERLRRLAEDEAFQRRRLEEQAAQHKADIEERLAQLRKASDSELERQKGLVEDTLRQRRQVEEEILALKASFEKAAAGKAELELELGRIRSNAEDTLRSKEQAELEAARQRQLAAEEERRRREAEERVQKSLAAEEEAARQRKAALEEVERLKAKVEEARRLRERAEQESARQLQLAQEAAQKRLQAEEKAHAFAVQQKEQELQQTLQQEQSVLDQLRGEAEAARRAAEEAEEARVQAEREAAQSRRQVEEAERLKQSAEEQAQARAQAQAAAEKLRKEAEQEAARRAQAEQAALRQKQAADAEMEKHKKFAEQTLRQKAQVEQELTTLRLQLEETDHQKNLLDEELQRLKAEATEAARQRSQVEEELFSVRVQMEELSKLKARIEAENRALILRDKDNTQRFLQEEAEKMKQVAEEAARLSVAAQEAARLRQLAEEDLAQQRALAEKMLKEKMQAVQEATRLKAEAELLQQQKELAQEQARRLQEDKEQMAQQLAEETQGFQRTLEAERQRQLEMSAEAERLKLRVAEMSRAQARAEEDAQRFRKQAEEIGEKLHRTELATQEKVTLVQTLEIQRQQSDHDAERLREAIAELEREKEKLQQEAKLLQLKSEEMQTVQQEQLLQETQALQQSFLSEKDSLLQRERFIEQEKAKLEQLFQDEVAKAQQLREEQQRQQQQMEQERQRLVASMEEARRRQHEAEEGVRRKQEELQQLEQQRRQQEELLAEENQRLREQLQLLEEQHRAALAHSEEVTASQVAATKTLPNGRDALDGPAAEAEPEHSFDGLRRKVSAQRLQEAGILSAEELQRLAQGHTTVDELARREDVRHYLQGRSSIAGLLLKATNEKLSVYAALQRQLLSPGTALILLEAQAASGFLLDPVRNRRLTVNEAVKEGVVGPELHHKLLSAERAVTGYKDPYTGQQISLFQAMQKGLIVREHGIRLLEAQIATGGVIDPVHSHRVPVDVAYRRGYFDEEMNRVLADPSDDTKGFFDPNTHENLTYLQLLERCVEDPETGLCLLPLTDKAAKGGELVYTDSEARDVFEKATVSAPFGKFQGKTVTIWEIINSEYFTAEQRRDLLRQFRTGRITVEKIIKIIITVVEEQEQKGRLCFEGLRSLVPAAELLESRVIDRELYQQLQRGERSVRDVAEVDTVRRALRGANVIAGVWLEEAGQKLSIYNALKKDLLPSDMAVALLEAQAGTGHIIDPATSARLTVDEAVRAGLVGPEFHEKLLSAEKAVTGYRDPYTGQSVSLFQALKKGLIPREQGLRLLDAQLSTGGIVDPSKSHRVPLDVACARGCLDEETSRALSAPRADAKAYSDPSTGEPATYGELQQRCRPDQLTGLSLLPLSEKAARARQEELYSELQARETFEKTPVEVPVGGFKGRTVTVWELISSEYFTAEQRQELLRQFRTGKVTVEKVIKILITIVEEVETLRQERLSFSGLRAPVPASELLASGVLSRAQFEQLKDGKTTVKDLSELGSVRTLLQGSGCLAGIYLEDTKEKVSIYEAMRRGLLRATTAALLLEAQAATGFLVDPVRNQRLYVHEAVKAGVVGPELHEQLLSAEKAVTGYRDPYSGSTISLFQAMQKGLVLRQHGIRLLEAQIATGGIIDPVHSHRVPVDVAYQRGYFSEEMNRVLADPSDDTKGFFDPNTHENLTYRQLLERCVEDPETGLRLLPLKGAEKAEVVETTQVYTEEETRRAFEETQIDIPGGGSHGGSTMSLWEVMQSDLIPEEQRAQLMADFQAGRVTKERMIIIIIEIIEKTEIIRQQGLASYDYVRRRLTAEDLFEARIISLETYNLLREGTRSLREALEAESAWCYLYGTGSVAGVYLPGSRQTLSIYQALKKGLLSAEVARLLLEAQAATGFLLDPVKGERLTVDEAVRKGLVGPELHDRLLSAERAVTGYRDPYTEQTISLFQAMKKELIPTEEALRLLDAQLATGGIVDPRLGFHLPLEVAYQRGYLNKDTHDQLSEPSEVRSYVDPSTDERLSYTQLLRRCRRDDGTGQLLLPLSDARKLTFRGLRKQITMEELVRSQVMDEATALQLREGLTSIEEVTKNLQKFLEGTSCIAGVFVDATKERLSVYQAMKKGIIRPGTAFELLEAQAATGYVIDPIKGLKLTVEEAVRMGIVGPEFKDKLLSAERAVTGYKDPYSGKLISLFQAMKKGLILKDHGIRLLEAQIATGGIIDPEESHRLPVEVAYKRGLFDEEMNEILTDPSDDTKGFFDPNTEENLTYLQLMERCITDPQTGLCLLPLKEKKRERKTSSKSSVRKRRVVIVDPETGKEMSVYEAYRKGLIDHQTYLELSEQECEWEEITISSSDGVVKSMIIDRRSGRQYDIDDAIAKNLIDRSALDQYRAGTLSITEFADMLSGNAGGFRSRSSSVGSSSSYPISPAVSRTQLASWSDPTEETGPVAGILDTETLEKVSITEAMHRNLVDNITGQRLLEAQACTGGIIDPSTGERFPVTDAVNKGLVDKIMVDRINLAQKAFCGFEDPRTKTKMSAAQALKKGWLYYEAGQRFLEVQYLTGGLIEPDTPGRVPLDEALQRGTVDARTAQKLRDVGAYSKYLTCPKTKLKISYKDALDRSMVEEGTGLRLLEAAAQSTKGYYSPYSVSGSGSTAGSRTGSRTGSRAGSRRGSFDATGSGFSMTFSSSSYSSSGYGRRYASGSSASLGGPESAVA',
      'accession': 'IPI00398776.3',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 197,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'D',
      'pre': 'R',
      'protein description': '>IPI:IPI00398776.3|TREMBL:Q6S379;Q96IE3|REFSEQ:NP_958783 Tax_Id=9606 plectin 1 isoform 7',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 181,
      'version': '3.15'}],
    'PeptideSequence': 'QTNLENLDQAFSVAER',
    'calculatedMassToCharge': 1834.8856,
    'chargeState': 1,
    'experimentalMassToCharge': 1834.884,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=3'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'HHTAAFEER',
      'Seq': 'MKIVPDERDRVQKKTFTKWVNKHLIKAQRHISDLYEDLRDGHNLISLLEVLSGDSLPREKGRMRFHKLQNVQIALDYLRHRQVKLVNIRNDDIADGNPKLTLGLIWTIILHFQISDIQVSGQSEDMTAKEKLLLWSQRMVEGYQGLRCDNFTSSWRDGRLFNAIIHRHKPLLIDMNKVYRQTNLENLDQAFSVAERDLGVTRLLDPEDVDVPQPDEKSIITYVSSLYDAMPRVPDVQDGVRANELQLRWQEYRELVLLLLQWMRHHTAAFEERRFPSSFEEIEILWSQFLKFKEMELPAKEADKNRSKGIYQSLEGAVQAGQLKVPPGYHPLDVEKEWGKLHVAILEREKQLRSEFERLECLQRIVTKLQMEAGLCEEQLNQADALLQSDVRLLAAGKVPQRAGEVERDLDKADSMIRLLFNDVQTLKDGRHPQGEQMYRRVYRLHERLVAIRTEYNLRLKAGVAAPATQVAQVTLQSVQRRPELEDSTLRYLQDLLAWVEENQHRVDGAEWGVDLPSVEAQLGSHRGLHQSIEEFRAKIERARSDEGQLSPATRGAYRDCLGRLDLQYAKLLNSSKARLRSLESLHSFVAAATKELMWLNEKEEEEVGFDWSDRNTNMTAKKESYSALMRELELKEKKIKELQNAGDRLLREDHPARPTVESFQAALQTQWSWMLQLCCCIEAHLKENAAYFQFFSDVREAEGQLQKLQEALRRKYSCDRSATVTRLEDLLQDAQDEKEQLNEYKGHLSGLAKRAKAVVQLKPRHPAHPMRGRLPLLAVCDYKQVEVTVHKGDECQLVGPAQPSHWKVLSSSGSEAAVPSVCFLVPPPNQEAQEAVTRLEAQHQALVTLWHQLHVDMKSLLAWQSLRRDVQLIRSWSLATFRTLKPEEQRQALHSLELHYQAFLRDSQDAGGFGPEDRLMAEREYGSCSHHYQQLLQSLEQGAQEESRCQRCISELKDIRLQLEACETRTVHRLRLPLDKEPARECAQRIAEQQKAQAEVEGLGKGVARLSAEAEKVLALPEPSPAAPTLRSELELTLGKLEQVRSLSAIYLEKLKTISLVIRGTQGAEEVLRAHEEQLKEAQAVPATLPELEATKASLKKLRAQAEAQQPTFDALRDELRGAQEVGERLQQRHGERDVEVERWRERVAQLLERWQAVLAQTDVRQRELEQLGRQLRYYRESADPLGAWLQDARRRQEQIQAMPLADSQAVREQLRQEQALLEEIERHGEKVEECQRFAKQYINAIKDYELQLVTYKAQLEPVASPAKKPKVQSGSESVIQEYVDLRTHYSELTTLTSQYIKFISETLRRMEEEERLAEQQRAEERERLAEVEAALEKQRQLAEAHAQAKAQAEREAKELQQRMQEEVVRREEAAVDAQQQKRSIQEELQQLRQSSEAEIQAKARQAEAAERSRLRIEEEIRVVRLQLEATERQRGGAEGELQALRARAEEAEAQKRQAQEEAERLRRQVQDESQRKRQAEVELASRVKAEAEAAREKQRALQALEELRLQAEEAERRLRQAEVERARQVQVALETAQRSAEAELQSKRASFAEKTAQLERSLQEEHVAVAQLREEAERRAQQQAEAERAREEAERELERWQLKANEALRLRLQAEEVAQQKSLAQAEAEKQKEEAEREARRRGKAEEQAVRQRELAEQELEKQRQLAEGTAQQRLAAEQELIRLRAETEQGEQQRQLLEEELARLQREAAAATQKRQELEAELAKVRAEMEVLLASKARAEEESRSTSEKSKQRLEAEAGRFRELAEEAARLRALAEEAKRQRQLAEEDAARQRAEAERVLAEKLAAIGEATRLKTEAEIALKEKEAENERLRRLAEDEAFQRRRLEEQAAQHKADIEERLAQLRKASDSELERQKGLVEDTLRQRRQVEEEILALKASFEKAAAGKAELELELGRIRSNAEDTLRSKEQAELEAARQRQLAAEEERRRREAEERVQKSLAAEEEAARQRKAALEEVERLKAKVEEARRLRERAEQESARQLQLAQEAAQKRLQAEEKAHAFAVQQKEQELQQTLQQEQSVLDQLRGEAEAARRAAEEAEEARVQAEREAAQSRRQVEEAERLKQSAEEQAQARAQAQAAAEKLRKEAEQEAARRAQAEQAALRQKQAADAEMEKHKKFAEQTLRQKAQVEQELTTLRLQLEETDHQKNLLDEELQRLKAEATEAARQRSQVEEELFSVRVQMEELSKLKARIEAENRALILRDKDNTQRFLQEEAEKMKQVAEEAARLSVAAQEAARLRQLAEEDLAQQRALAEKMLKEKMQAVQEATRLKAEAELLQQQKELAQEQARRLQEDKEQMAQQLAEETQGFQRTLEAERQRQLEMSAEAERLKLRVAEMSRAQARAEEDAQRFRKQAEEIGEKLHRTELATQEKVTLVQTLEIQRQQSDHDAERLREAIAELEREKEKLQQEAKLLQLKSEEMQTVQQEQLLQETQALQQSFLSEKDSLLQRERFIEQEKAKLEQLFQDEVAKAQQLREEQQRQQQQMEQERQRLVASMEEARRRQHEAEEGVRRKQEELQQLEQQRRQQEELLAEENQRLREQLQLLEEQHRAALAHSEEVTASQVAATKTLPNGRDALDGPAAEAEPEHSFDGLRRKVSAQRLQEAGILSAEELQRLAQGHTTVDELARREDVRHYLQGRSSIAGLLLKATNEKLSVYAALQRQLLSPGTALILLEAQAASGFLLDPVRNRRLTVNEAVKEGVVGPELHHKLLSAERAVTGYKDPYTGQQISLFQAMQKGLIVREHGIRLLEAQIATGGVIDPVHSHRVPVDVAYRRGYFDEEMNRVLADPSDDTKGFFDPNTHENLTYLQLLERCVEDPETGLCLLPLTDKAAKGGELVYTDSEARDVFEKATVSAPFGKFQGKTVTIWEIINSEYFTAEQRRDLLRQFRTGRITVEKIIKIIITVVEEQEQKGRLCFEGLRSLVPAAELLESRVIDRELYQQLQRGERSVRDVAEVDTVRRALRGANVIAGVWLEEAGQKLSIYNALKKDLLPSDMAVALLEAQAGTGHIIDPATSARLTVDEAVRAGLVGPEFHEKLLSAEKAVTGYRDPYTGQSVSLFQALKKGLIPREQGLRLLDAQLSTGGIVDPSKSHRVPLDVACARGCLDEETSRALSAPRADAKAYSDPSTGEPATYGELQQRCRPDQLTGLSLLPLSEKAARARQEELYSELQARETFEKTPVEVPVGGFKGRTVTVWELISSEYFTAEQRQELLRQFRTGKVTVEKVIKILITIVEEVETLRQERLSFSGLRAPVPASELLASGVLSRAQFEQLKDGKTTVKDLSELGSVRTLLQGSGCLAGIYLEDTKEKVSIYEAMRRGLLRATTAALLLEAQAATGFLVDPVRNQRLYVHEAVKAGVVGPELHEQLLSAEKAVTGYRDPYSGSTISLFQAMQKGLVLRQHGIRLLEAQIATGGIIDPVHSHRVPVDVAYQRGYFSEEMNRVLADPSDDTKGFFDPNTHENLTYRQLLERCVEDPETGLRLLPLKGAEKAEVVETTQVYTEEETRRAFEETQIDIPGGGSHGGSTMSLWEVMQSDLIPEEQRAQLMADFQAGRVTKERMIIIIIEIIEKTEIIRQQGLASYDYVRRRLTAEDLFEARIISLETYNLLREGTRSLREALEAESAWCYLYGTGSVAGVYLPGSRQTLSIYQALKKGLLSAEVARLLLEAQAATGFLLDPVKGERLTVDEAVRKGLVGPELHDRLLSAERAVTGYRDPYTEQTISLFQAMKKELIPTEEALRLLDAQLATGGIVDPRLGFHLPLEVAYQRGYLNKDTHDQLSEPSEVRSYVDPSTDERLSYTQLLRRCRRDDGTGQLLLPLSDARKLTFRGLRKQITMEELVRSQVMDEATALQLREGLTSIEEVTKNLQKFLEGTSCIAGVFVDATKERLSVYQAMKKGIIRPGTAFELLEAQAATGYVIDPIKGLKLTVEEAVRMGIVGPEFKDKLLSAERAVTGYKDPYSGKLISLFQAMKKGLILKDHGIRLLEAQIATGGIIDPEESHRLPVEVAYKRGLFDEEMNEILTDPSDDTKGFFDPNTEENLTYLQLMERCITDPQTGLCLLPLKEKKRERKTSSKSSVRKRRVVIVDPETGKEMSVYEAYRKGLIDHQTYLELSEQECEWEEITISSSDGVVKSMIIDRRSGRQYDIDDAIAKNLIDRSALDQYRAGTLSITEFADMLSGNAGGFRSRSSSVGSSSSYPISPAVSRTQLASWSDPTEETGPVAGILDTETLEKVSITEAMHRNLVDNITGQRLLEAQACTGGIIDPSTGERFPVTDAVNKGLVDKIMVDRINLAQKAFCGFEDPRTKTKMSAAQALKKGWLYYEAGQRFLEVQYLTGGLIEPDTPGRVPLDEALQRGTVDARTAQKLRDVGAYSKYLTCPKTKLKISYKDALDRSMVEEGTGLRLLEAAAQSTKGYYSPYSVSGSGSTAGSRTGSRTGSRAGSRRGSFDATGSGFSMTFSSSSYSSSGYGRRYASGSSASLGGPESAVA',
      'accession': 'IPI00398776.3',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 274,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'R',
      'pre': 'R',
      'protein description': '>IPI:IPI00398776.3|TREMBL:Q6S379;Q96IE3|REFSEQ:NP_958783 Tax_Id=9606 plectin 1 isoform 7',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 265,
      'version': '3.15'}],
    'PeptideSequence': 'HHTAAFEER',
    'calculatedMassToCharge': 1097.5049,
    'chargeState': 1,
    'experimentalMassToCharge': 1097.503,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=4'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'STFSTNYR',
      'Seq': 'MSFTTRSTFSTNYRSLGSVQAPSYGARPVSSAASVYAGAGGSGSRISVSRSTSFRGGMGSGGLATGIAGGLAGMGGIQNEKETMQSLNDRLASYLDRVRSLETENRRLESKIREHLEKKGPQVRDWSHYFKIIEDLRAQIFANTVDNARIVLQIDNARLAADDFRVKYETELAMRQSVENDIHGLRKVIDDTNITRLQLETEIEALKEELLFMKKNHEEEVKGLQAQIASSGLTVEVDAPKSQDLAKIMADIRAQYDELARKNREELDKYWSQQIEESTTVVTTQSAEVGAAETTLTELRRTVQSLEIDLDSMRNLKASLENSLREVEARYALQMEQLNGILLHLESELAQTRAEGQRQAQEYEALLNIKVKLEAEIATYRRLLEDGEDFNLGDALDSSNSMQTIQKTTTRRIVDGKVVSETNDTKVLRH',
      'accession': 'IPI00554788.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 15,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'S',
      'pre': 'R',
      'protein description': '>IPI:IPI00554788.5|SWISS-PROT:P05783|ENSEMBL:ENSP00000373487;ENSP00000373489|REFSEQ:NP_000215;NP_954657|H-INV:HIT000280941|VEGA:OTTHUMP00000167632 Tax_Id=9606 Gene_Symbol=KRT18 Keratin, type I cytoskeletal 18',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 7,
      'version': '3.15'}],
    'PeptideSequence': 'STFSTNYR',
    'calculatedMassToCharge': 975.4457,
    'chargeState': 1,
    'experimentalMassToCharge': 975.446,
    'passThreshold': True,
    'rank': 1},
   {'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'MYGPMGTR',
      'Seq': 'PSKYTHAFFHGGTVLFTYVDGLIAESLQLVTQSPPAAGVAGMYDGTSPTTTDIADFEGGPVKEDDEQKLLSSCPRVKGSEPKSPDHGACPSKGLNCKEAHAACCAVFYDYGVEVELVSALSATGAVVHKTASCTLDVTYPEDTIDGDPTAGRKTKKCKGSKATPPDYVRGEKVEIAARGPNDKLYYFEVVSREKPLGAFKCGNQKVNIVYEGVVVVGELEAKILDEVQGTTDGVVGSKDTTQINVIVFNLPCKTGSFVCNRAYKCDKPMDAEGPVVAKLNPGRAALVLHHPEQDKGLNLTGGVHNDTPDGVQKGLDITPTSVAPPMKQQVHNVVMRKKDTLDSKAQIATPETAFVNADAEPVSPWSELIVSEKLGENALGTLQPFHQAVDTTVAKPYRAPLAPWGAVVVNEQFVPAVSVNIGAERESEYILQTAGKCIADDLEGITETNKAVTTREDGPSISYIPSGGDAVSYDTQNRVGTTSLSPWKVDRGVSLSVGALKLLRIVWNDFCADTPVCVAGEVSYSTVGRGVSAGVAAPNPPVKAMVSRPIGTVSRIGGSDTRAGMKFSMHTGGIHTTKSKDDGESGSSYGGDTTVIEYGVEGGSTTVQELAIAPVGAYNLSAQPFGVKGRNEETKKTYSFQVAFVFGVLIFPESPRSREIQNPPAPIVYFVKSGDAQDKGGKEKAGTALIPFMVDPASGLKMYGPMGTRNQNDLGQESQGGTPSKTSEDDVSYNETKQLRATGGAGEETSDADSPKRLSEHGASASPMVQMGIGVINLEYGAPSVTPTVEPCRVTEYVSSSDSEGYAGTRVSAGVDQIDVKPLITLQIYPRSLYQVQENKCLATQAAIVYSSADVVPVVVLNKSGHGKFKVDRTDRKQHEVHYGNKCDDTNGDKNIGGNPSTVLESKDCCGISCVPLKVKTGKGVGPVTMSPPMGPAVHGGDIVHSLREVVVVSAVGKSDVVRGAGVAESKVISKRVAVTMADFSYVEKGIGRKGFSETDFGHKGPGDGRVVGSSRKVSSFFVIFQPAGGWKVIEVILHDAIIGGDGQIGGTANPFVGYTLKEASGVDYADVPVIGVLAYYVAELYRDQHGTDQGPGPEGNEITADPGVGTGAEDGRASGYGAGIVTTKTTDSTGCPHRPVQAERLGRKLRSEPVMGVKPGVGGTHCNEDINEKTGIALDVVRAPPAFQPSISGVHTKSSATDVGPDVFDTGGVALVCQPVVGSVVSPYYCPPFGAGVIECYPMSTDPADSSRRNFKPPQRVVTTTEAGDDSGAYVYRYFGPGADMKLPKDSSDVVGNGDCESDPPKLSGNVPQHPEQYSTPAESMRGDPAVSDSLVMANVEFPKCEPDQNYGGHDGKVAPFFDRENEQVDVGLPNDSKGPCVRGVFPLFHYIGSVAPRAVIKCPTTLGPIGQTGGFPGFKSIAYLLIGTGCFQKLLKYVITELVDNCDGCRAKYGSDSTGSFVMEAKGLPIQGFKGKSGTDKCNHEKVDIELTTSGKRPRPPANQAKIEDVLPNAVTDVKECTAVYVDREIELDEIDPHTAQGHRYKRGPKEPIAWSIELSPSGRYMVELLVEISVAFVPPIPIFGTEVAPVGAPAISTSGSPGPAIGRVTLGQKAALPTEPEPSNSYARVDRQEEKRTPEGCGEAAKAHHPPFGINPLAQVIEDQDAYHFDHVGARIGLERGTSCDGESEAIEGPVLYAAPAKAAPSGEVHIARQDVKDPLAGGELHTVLDRCDAVSYESSKSQPLHTITFSKPEPGKSDAMITPPVIEPIVFIWIQRAHFPNGETSLGSSRAFAGKRVSKTYGGSDLRECWIGGGPKKNLKPCQPGEGTGKPITGEPLGMVIVRTLPRWELVKHFLVAPGTVIGTTGHADHVSRPGKPVLIPTERANWPVPRHYTELHDGREVKCTREGVKFHRLDTVNAAVHKNYRHPSSKSSCLWHGVVTKEQAGQISIREFVEDVSPGSIIVDIVNLVAVQGPSSTGSGLGVVHAYPLTYYTVKDIVVALKLSSASFIMVNKKAVVTVCFSDVQSGFKKNVASPPGVLSVSIGLDTYEGDPGIATNWWPSTDEKPCGNVLEDSGPDENHSNPNTAWEFTGLGDTKEGRPNTAFVESEMVLLPVAYVLEQKHPGQGQVGNTMLKDGICEGSTSHVGAVDPSEVQPLGFPGRLITKKFLETFIFCYPSEPIGKGKKVDGKLTSSYSSELAERELVLALAVGIGDAVYYYAFGAGPKIHVFTGDGGGVKNGILVLEGPFHGDEPDLGPFNPGPTQGVERGYSGGEKLATPTVTTYVPELVGLVVVGGTDGIGVHAAVVERWGTYDGKVSPQSVYTTKPGPLSGSDDIHLNVKTVKYLHDEGYTFTIPPHGEKVVEVVEAEQVGRQSDGTTYVTQNNAQAIPVKLRRTAPYGELGHVKLDQVGEEYFGIKFHVNGCDGPGTGPENATYVEQTSGVPPRTPVFGFSVEGTLIQSPQIALNKGRHAVTTIIKQARPFLGGVKGTTDQTPDAFVPHKQTEPLVAACKYVGGWYNHVVPKGKAGEGQGQHRPAVKRANPSDEQAMQSMKKPSPPTPQGEEVSTSVKDLEPESYFQQNVYVNVPAHIGKKLPGIECNQND',
      'accession': 'SHD00644576.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 710,
      'isDecoy': True,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'N',
      'pre': 'K',
      'protein description': '>SHD:SHD00644576.1|TREMBL:Q5HY54;Q86TQ3;Q96C61|ENSEMBL:ENSP00000358863|VEGA:OTTHUMP00000064890 Tax_Id=9606 Gene_Symbol=FLNA Filamin A, alpha',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 702,
      'version': '3.15'}],
    'PeptideSequence': 'MYGPMGTR',
    'calculatedMassToCharge': 912.3993,
    'chargeState': 1,
    'experimentalMassToCharge': 912.29,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=6'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'Modification': [{'location': 11,
      'name': 'Oxidation'}],
    'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'Modification': [{'location': 11, 'name': 'Oxidation'}],
      'PeptideSequence': 'TLTLVDTGIGMTK',
      'Seq': 'PEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYESLTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEALQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEPIGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEEEKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWTRNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKKKKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRKNIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGDEMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCVQQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTISNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETLRQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVAAEEPNAAVPDEIPPLEGDEDASRMEEVD',
      'accession': 'IPI00414676.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 50,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'A',
      'pre': 'R',
      'protein description': '>IPI:IPI00414676.5|SWISS-PROT:P08238|TREMBL:Q5T9W7;Q6PK50;Q9H6X9|ENSEMBL:ENSP00000325875|REFSEQ:NP_031381|H-INV:HIT000008644;HIT000032091;HIT000034201;HIT000035963;HIT000036733;HIT000049765;HIT000057726|VEGA:OTTHUMP00000016517;OTTHUMP00000016518;OTTHUMP00000016519 Tax_Id=9606 Heat shock protein HSP 90-beta',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 41,
      'version': '3.15'}],
    'PeptideSequence': 'TLTLVDTGIGMTK',
    'ProteinScape:IntensityCoverage': 0.0,
    'ProteinScape:MascotScore': 33.82,
    'calculatedMassToCharge': 1365.722015,
    'chargeState': 1,
    'experimentalMassToCharge': 1365.721,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=11'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'HNDDEQYAWESSAGGSFTVR',
      'Seq': 'PEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYESLTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEALQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEPIGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEEEKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWTRNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKKKKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRKNIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGDEMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCVQQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTISNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETLRQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVAAEEPNAAVPDEIPPLEGDEDASRMEEVD',
      'accession': 'IPI00414676.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 50,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'A',
      'pre': 'K',
      'protein description': '>IPI:IPI00414676.5|SWISS-PROT:P08238|TREMBL:Q5T9W7;Q6PK50;Q9H6X9|ENSEMBL:ENSP00000325875|REFSEQ:NP_031381|H-INV:HIT000008644;HIT000032091;HIT000034201;HIT000035963;HIT000036733;HIT000049765;HIT000057726|VEGA:OTTHUMP00000016517;OTTHUMP00000016518;OTTHUMP00000016519 Tax_Id=9606 Heat shock protein HSP 90-beta',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 41,
      'version': '3.15'}],
    'PeptideSequence': 'HNDDEQYAWESSAGGSFTVR',
    'ProteinScape:IntensityCoverage': 0.0,
    'ProteinScape:MascotScore': 39.0,
    'calculatedMassToCharge': 2256.9515,
    'chargeState': 1,
    'experimentalMassToCharge': 2256.952,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=12'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'GGMGSGGLATGIAGGLAGMGGIQNEK',
      'Seq': 'MSFTTRSTFSTNYRSLGSVQAPSYGARPVSSAASVYAGAGGSGSRISVSRSTSFRGGMGSGGLATGIAGGLAGMGGIQNEKETMQSLNDRLASYLDRVRSLETENRRLESKIREHLEKKGPQVRDWSHYFKIIEDLRAQIFANTVDNARIVLQIDNARLAADDFRVKYETELAMRQSVENDIHGLRKVIDDTNITRLQLETEIEALKEELLFMKKNHEEEVKGLQAQIASSGLTVEVDAPKSQDLAKIMADIRAQYDELARKNREELDKYWSQQIEESTTVVTTQSAEVGAAETTLTELRRTVQSLEIDLDSMRNLKASLENSLREVEARYALQMEQLNGILLHLESELAQTRAEGQRQAQEYEALLNIKVKLEAEIATYRRLLEDGEDFNLGDALDSSNSMQTIQKTTTRRIVDGKVVSETNDTKVLRH',
      'accession': 'IPI00554788.5',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 81,
      'isDecoy': False,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'E',
      'pre': 'R',
      'protein description': '>IPI:IPI00554788.5|SWISS-PROT:P05783|ENSEMBL:ENSP00000373487;ENSP00000373489|REFSEQ:NP_000215;NP_954657|H-INV:HIT000280941|VEGA:OTTHUMP00000167632 Tax_Id=9606 Gene_Symbol=KRT18 Keratin, type I cytoskeletal 18',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 55,
      'version': '3.15'}],
    'PeptideSequence': 'GGMGSGGLATGIAGGLAGMGGIQNEK',
    'calculatedMassToCharge': 2261.0939,
    'chargeState': 1,
    'experimentalMassToCharge': 2261.092,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=35'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'LRSEPVMGVK',
      'Seq': 'PSKYTHAFFHGGTVLFTYVDGLIAESLQLVTQSPPAAGVAGMYDGTSPTTTDIADFEGGPVKEDDEQKLLSSCPRVKGSEPKSPDHGACPSKGLNCKEAHAACCAVFYDYGVEVELVSALSATGAVVHKTASCTLDVTYPEDTIDGDPTAGRKTKKCKGSKATPPDYVRGEKVEIAARGPNDKLYYFEVVSREKPLGAFKCGNQKVNIVYEGVVVVGELEAKILDEVQGTTDGVVGSKDTTQINVIVFNLPCKTGSFVCNRAYKCDKPMDAEGPVVAKLNPGRAALVLHHPEQDKGLNLTGGVHNDTPDGVQKGLDITPTSVAPPMKQQVHNVVMRKKDTLDSKAQIATPETAFVNADAEPVSPWSELIVSEKLGENALGTLQPFHQAVDTTVAKPYRAPLAPWGAVVVNEQFVPAVSVNIGAERESEYILQTAGKCIADDLEGITETNKAVTTREDGPSISYIPSGGDAVSYDTQNRVGTTSLSPWKVDRGVSLSVGALKLLRIVWNDFCADTPVCVAGEVSYSTVGRGVSAGVAAPNPPVKAMVSRPIGTVSRIGGSDTRAGMKFSMHTGGIHTTKSKDDGESGSSYGGDTTVIEYGVEGGSTTVQELAIAPVGAYNLSAQPFGVKGRNEETKKTYSFQVAFVFGVLIFPESPRSREIQNPPAPIVYFVKSGDAQDKGGKEKAGTALIPFMVDPASGLKMYGPMGTRNQNDLGQESQGGTPSKTSEDDVSYNETKQLRATGGAGEETSDADSPKRLSEHGASASPMVQMGIGVINLEYGAPSVTPTVEPCRVTEYVSSSDSEGYAGTRVSAGVDQIDVKPLITLQIYPRSLYQVQENKCLATQAAIVYSSADVVPVVVLNKSGHGKFKVDRTDRKQHEVHYGNKCDDTNGDKNIGGNPSTVLESKDCCGISCVPLKVKTGKGVGPVTMSPPMGPAVHGGDIVHSLREVVVVSAVGKSDVVRGAGVAESKVISKRVAVTMADFSYVEKGIGRKGFSETDFGHKGPGDGRVVGSSRKVSSFFVIFQPAGGWKVIEVILHDAIIGGDGQIGGTANPFVGYTLKEASGVDYADVPVIGVLAYYVAELYRDQHGTDQGPGPEGNEITADPGVGTGAEDGRASGYGAGIVTTKTTDSTGCPHRPVQAERLGRKLRSEPVMGVKPGVGGTHCNEDINEKTGIALDVVRAPPAFQPSISGVHTKSSATDVGPDVFDTGGVALVCQPVVGSVVSPYYCPPFGAGVIECYPMSTDPADSSRRNFKPPQRVVTTTEAGDDSGAYVYRYFGPGADMKLPKDSSDVVGNGDCESDPPKLSGNVPQHPEQYSTPAESMRGDPAVSDSLVMANVEFPKCEPDQNYGGHDGKVAPFFDRENEQVDVGLPNDSKGPCVRGVFPLFHYIGSVAPRAVIKCPTTLGPIGQTGGFPGFKSIAYLLIGTGCFQKLLKYVITELVDNCDGCRAKYGSDSTGSFVMEAKGLPIQGFKGKSGTDKCNHEKVDIELTTSGKRPRPPANQAKIEDVLPNAVTDVKECTAVYVDREIELDEIDPHTAQGHRYKRGPKEPIAWSIELSPSGRYMVELLVEISVAFVPPIPIFGTEVAPVGAPAISTSGSPGPAIGRVTLGQKAALPTEPEPSNSYARVDRQEEKRTPEGCGEAAKAHHPPFGINPLAQVIEDQDAYHFDHVGARIGLERGTSCDGESEAIEGPVLYAAPAKAAPSGEVHIARQDVKDPLAGGELHTVLDRCDAVSYESSKSQPLHTITFSKPEPGKSDAMITPPVIEPIVFIWIQRAHFPNGETSLGSSRAFAGKRVSKTYGGSDLRECWIGGGPKKNLKPCQPGEGTGKPITGEPLGMVIVRTLPRWELVKHFLVAPGTVIGTTGHADHVSRPGKPVLIPTERANWPVPRHYTELHDGREVKCTREGVKFHRLDTVNAAVHKNYRHPSSKSSCLWHGVVTKEQAGQISIREFVEDVSPGSIIVDIVNLVAVQGPSSTGSGLGVVHAYPLTYYTVKDIVVALKLSSASFIMVNKKAVVTVCFSDVQSGFKKNVASPPGVLSVSIGLDTYEGDPGIATNWWPSTDEKPCGNVLEDSGPDENHSNPNTAWEFTGLGDTKEGRPNTAFVESEMVLLPVAYVLEQKHPGQGQVGNTMLKDGICEGSTSHVGAVDPSEVQPLGFPGRLITKKFLETFIFCYPSEPIGKGKKVDGKLTSSYSSELAERELVLALAVGIGDAVYYYAFGAGPKIHVFTGDGGGVKNGILVLEGPFHGDEPDLGPFNPGPTQGVERGYSGGEKLATPTVTTYVPELVGLVVVGGTDGIGVHAAVVERWGTYDGKVSPQSVYTTKPGPLSGSDDIHLNVKTVKYLHDEGYTFTIPPHGEKVVEVVEAEQVGRQSDGTTYVTQNNAQAIPVKLRRTAPYGELGHVKLDQVGEEYFGIKFHVNGCDGPGTGPENATYVEQTSGVPPRTPVFGFSVEGTLIQSPQIALNKGRHAVTTIIKQARPFLGGVKGTTDQTPDAFVPHKQTEPLVAACKYVGGWYNHVVPKGKAGEGQGQHRPAVKRANPSDEQAMQSMKKPSPPTPQGEEVSTSVKDLEPESYFQQNVYVNVPAHIGKKLPGIECNQND',
      'accession': 'SHD00644576.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 1159,
      'isDecoy': True,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'P',
      'pre': 'K',
      'protein description': '>SHD:SHD00644576.1|TREMBL:Q5HY54;Q86TQ3;Q96C61|ENSEMBL:ENSP00000358863|VEGA:OTTHUMP00000064890 Tax_Id=9606 Gene_Symbol=FLNA Filamin A, alpha',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 1150,
      'version': '3.15'}],
    'PeptideSequence': 'LRSEPVMGVK',
    'calculatedMassToCharge': 1115.6168,
    'chargeState': 1,
    'experimentalMassToCharge': 1115.617,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=36'},
 {'FileFormat': 'Proteinscape spectra',
  'SpectrumIDFormat': 'spectrum from database nativeID format',
  'SpectrumIdentificationItem': [{'PeptideEvidenceRef': [{'DatabaseName': 'database IPI_human',
      'PeptideSequence': 'QSDGTTYVTQNNAQAIPVK',
      'Seq': 'PSKYTHAFFHGGTVLFTYVDGLIAESLQLVTQSPPAAGVAGMYDGTSPTTTDIADFEGGPVKEDDEQKLLSSCPRVKGSEPKSPDHGACPSKGLNCKEAHAACCAVFYDYGVEVELVSALSATGAVVHKTASCTLDVTYPEDTIDGDPTAGRKTKKCKGSKATPPDYVRGEKVEIAARGPNDKLYYFEVVSREKPLGAFKCGNQKVNIVYEGVVVVGELEAKILDEVQGTTDGVVGSKDTTQINVIVFNLPCKTGSFVCNRAYKCDKPMDAEGPVVAKLNPGRAALVLHHPEQDKGLNLTGGVHNDTPDGVQKGLDITPTSVAPPMKQQVHNVVMRKKDTLDSKAQIATPETAFVNADAEPVSPWSELIVSEKLGENALGTLQPFHQAVDTTVAKPYRAPLAPWGAVVVNEQFVPAVSVNIGAERESEYILQTAGKCIADDLEGITETNKAVTTREDGPSISYIPSGGDAVSYDTQNRVGTTSLSPWKVDRGVSLSVGALKLLRIVWNDFCADTPVCVAGEVSYSTVGRGVSAGVAAPNPPVKAMVSRPIGTVSRIGGSDTRAGMKFSMHTGGIHTTKSKDDGESGSSYGGDTTVIEYGVEGGSTTVQELAIAPVGAYNLSAQPFGVKGRNEETKKTYSFQVAFVFGVLIFPESPRSREIQNPPAPIVYFVKSGDAQDKGGKEKAGTALIPFMVDPASGLKMYGPMGTRNQNDLGQESQGGTPSKTSEDDVSYNETKQLRATGGAGEETSDADSPKRLSEHGASASPMVQMGIGVINLEYGAPSVTPTVEPCRVTEYVSSSDSEGYAGTRVSAGVDQIDVKPLITLQIYPRSLYQVQENKCLATQAAIVYSSADVVPVVVLNKSGHGKFKVDRTDRKQHEVHYGNKCDDTNGDKNIGGNPSTVLESKDCCGISCVPLKVKTGKGVGPVTMSPPMGPAVHGGDIVHSLREVVVVSAVGKSDVVRGAGVAESKVISKRVAVTMADFSYVEKGIGRKGFSETDFGHKGPGDGRVVGSSRKVSSFFVIFQPAGGWKVIEVILHDAIIGGDGQIGGTANPFVGYTLKEASGVDYADVPVIGVLAYYVAELYRDQHGTDQGPGPEGNEITADPGVGTGAEDGRASGYGAGIVTTKTTDSTGCPHRPVQAERLGRKLRSEPVMGVKPGVGGTHCNEDINEKTGIALDVVRAPPAFQPSISGVHTKSSATDVGPDVFDTGGVALVCQPVVGSVVSPYYCPPFGAGVIECYPMSTDPADSSRRNFKPPQRVVTTTEAGDDSGAYVYRYFGPGADMKLPKDSSDVVGNGDCESDPPKLSGNVPQHPEQYSTPAESMRGDPAVSDSLVMANVEFPKCEPDQNYGGHDGKVAPFFDRENEQVDVGLPNDSKGPCVRGVFPLFHYIGSVAPRAVIKCPTTLGPIGQTGGFPGFKSIAYLLIGTGCFQKLLKYVITELVDNCDGCRAKYGSDSTGSFVMEAKGLPIQGFKGKSGTDKCNHEKVDIELTTSGKRPRPPANQAKIEDVLPNAVTDVKECTAVYVDREIELDEIDPHTAQGHRYKRGPKEPIAWSIELSPSGRYMVELLVEISVAFVPPIPIFGTEVAPVGAPAISTSGSPGPAIGRVTLGQKAALPTEPEPSNSYARVDRQEEKRTPEGCGEAAKAHHPPFGINPLAQVIEDQDAYHFDHVGARIGLERGTSCDGESEAIEGPVLYAAPAKAAPSGEVHIARQDVKDPLAGGELHTVLDRCDAVSYESSKSQPLHTITFSKPEPGKSDAMITPPVIEPIVFIWIQRAHFPNGETSLGSSRAFAGKRVSKTYGGSDLRECWIGGGPKKNLKPCQPGEGTGKPITGEPLGMVIVRTLPRWELVKHFLVAPGTVIGTTGHADHVSRPGKPVLIPTERANWPVPRHYTELHDGREVKCTREGVKFHRLDTVNAAVHKNYRHPSSKSSCLWHGVVTKEQAGQISIREFVEDVSPGSIIVDIVNLVAVQGPSSTGSGLGVVHAYPLTYYTVKDIVVALKLSSASFIMVNKKAVVTVCFSDVQSGFKKNVASPPGVLSVSIGLDTYEGDPGIATNWWPSTDEKPCGNVLEDSGPDENHSNPNTAWEFTGLGDTKEGRPNTAFVESEMVLLPVAYVLEQKHPGQGQVGNTMLKDGICEGSTSHVGAVDPSEVQPLGFPGRLITKKFLETFIFCYPSEPIGKGKKVDGKLTSSYSSELAERELVLALAVGIGDAVYYYAFGAGPKIHVFTGDGGGVKNGILVLEGPFHGDEPDLGPFNPGPTQGVERGYSGGEKLATPTVTTYVPELVGLVVVGGTDGIGVHAAVVERWGTYDGKVSPQSVYTTKPGPLSGSDDIHLNVKTVKYLHDEGYTFTIPPHGEKVVEVVEAEQVGRQSDGTTYVTQNNAQAIPVKLRRTAPYGELGHVKLDQVGEEYFGIKFHVNGCDGPGTGPENATYVEQTSGVPPRTPVFGFSVEGTLIQSPQIALNKGRHAVTTIIKQARPFLGGVKGTTDQTPDAFVPHKQTEPLVAACKYVGGWYNHVVPKGKAGEGQGQHRPAVKRANPSDEQAMQSMKKPSPPTPQGEEVSTSVKDLEPESYFQQNVYVNVPAHIGKKLPGIECNQND',
      'accession': 'SHD00644576.1',
      'decoy DB accession regexp': '^SHD',
      'decoy DB generation algorithm': 'PeakQuant.DecoyDatabaseBuilder',
      'end': 2397,
      'isDecoy': True,
      'location': 'file://www.medizinisches-proteom-center.de/DBServer/ipi.HUMAN/3.15/ipi.HUMAN_decoy.fasta',
      'name': ['decoy DB from IPI_human', 'DB composition target+decoy', 'decoy DB type shuffle'],
      'numDatabaseSequences': 58099,
      'post': 'L',
      'pre': 'R',
      'protein description': '>SHD:SHD00644576.1|TREMBL:Q5HY54;Q86TQ3;Q96C61|ENSEMBL:ENSP00000358863|VEGA:OTTHUMP00000064890 Tax_Id=9606 Gene_Symbol=FLNA Filamin A, alpha',
      'releaseDate': '2006-02-22T09:30:47Z',
      'start': 2378,
      'version': '3.15'}],
    'PeptideSequence': 'QSDGTTYVTQNNAQAIPVK',
    'calculatedMassToCharge': 2035.0017,
    'chargeState': 1,
    'experimentalMassToCharge': 2035.002,
    'passThreshold': True,
    'rank': 1}],
  'location': 'proteinscape://www.medizinisches-proteom-center.de/PSServer/Project/Sample/Separation_1D_LC/Fraction_X',
  'spectrumID': 'databasekey=40'}]}
 
mzml_mz_array = np.load('test_mzml_mz.npy')
mzml_int_array = np.load('test_mzml_intensity.npy')
mzml_spectra = [{'MSn spectrum': '',
  'base peak intensity': 1471973.875,
  'base peak m/z': 810.415283203125,
  'count': 2,
  'defaultArrayLength': 19914,
  'highest observed m/z': 2000.0099466203771,
  'id': 'controllerType=0 controllerNumber=1 scan=1',
  'index': 0,
  'intensity array': makeCA(mzml_int_array),
  'lowest observed m/z': 200.00018816645022,
  'm/z array': makeCA(mzml_mz_array),
  'ms level': 1,
  'positive scan': '',
  'profile spectrum': '',
  'scanList': {'count': 1,
   'no combination': '',
   'scan': [{'[Thermo Trailer Extra]Monoisotopic M/Z:': 810.4152221679688,
     'filter string': 'FTMS + p ESI Full ms [200.00-2000.00]',
     'instrumentConfigurationRef': 'IC1',
     'preset scan configuration': 1.0,
     'scan start time': 0.004935,
     'scanWindowList': {'count': 1,
      'scanWindow': [{'scan window lower limit': 200.0,
        'scan window upper limit': 2000.0}]}}]},
  'total ion current': 15245068.0},
 {'MSn spectrum': '',
  'base peak intensity': 1471973.875,
  'base peak m/z': 810.415283203125,
  'count': 2,
  'defaultArrayLength': 19914,
  'highest observed m/z': 2000.0099466203771,
  'id': 'controllerType=0 controllerNumber=1 scan=1',
  'index': 1,
  'intensity array': makeCA(mzml_int_array),
  'lowest observed m/z': 200.00018816645022,
  'm/z array': makeCA(mzml_mz_array),
  'ms level': 1,
  'positive scan': '',
  'profile spectrum': '',
  'scanList': {'count': 1,
   'no combination': '',
   'scan': [{'[Thermo Trailer Extra]Monoisotopic M/Z:': 810.4152221679688,
     'filter string': 'FTMS + p ESI Full ms [200.00-2000.00]',
     'instrumentConfigurationRef': 'IC1',
     'preset scan configuration': 1.0,
     'scan start time': 0.004935,
     'scanWindowList': {'count': 1,
      'scanWindow': [{'scan window lower limit': 200.0,
        'scan window upper limit': 2000.0}]}}]},
  'total ion current': 15245068.0}]

mgf_int = [np.array([  73.,   44.,   67.,  291.,   54.,   49.]),
        np.array([  237.,   128.,   108.,  1007.,   974.,    79.])]
mgf_mz = [np.array([  846.6,   846.8,   847.6,  1640.1,  1640.6,  1895.5]),
        np.array([  345.1,   370.2,   460.2,  1673.3,  1674. ,  1675.3])]
mgf_ch = [np.ma.masked_equal([0]*6, 0),
        np.array([ 3.,  2.,  1.,  1.,  1.,  1.])]

mgf_spectra_long = [{'intensity array': makeCA(mgf_int[0]),
  'm/z array': makeCA(mgf_mz[0]),
  'charge array': makeCA(mgf_ch[0]),
  'params': {'charge': [2],
   'com': 'Based on http://www.matrixscience.com/help/data_file_help.html',
   'it_mods': 'Oxidation (M)',
   'itol': '1',
   'itolu': 'Da',
   'mass': 'Monoisotopic',
   'mods': 'Carbamidomethyl (C)',
   'pepmass': (983.6, None),
   'title': 'Spectrum 1',
   'useremail': 'leu@altered-state.edu',
   'username': 'Lou Scene'}},
 {'intensity array': makeCA(mgf_int[1]),
  'm/z array': makeCA(mgf_mz[1]),
  'charge array': makeCA(mgf_ch[1]),
  'params': {'charge': [2, 3],
   'com': 'Based on http://www.matrixscience.com/help/data_file_help.html',
   'it_mods': 'Oxidation (M)',
   'itol': '1',
   'itolu': 'Da',
   'mass': 'Monoisotopic',
   'mods': 'Carbamidomethyl (C)',
   'pepmass': (1084.9, 1234.0),
   'rtinseconds': '25',
   'scans': '3',
   'title': 'Spectrum 2',
   'useremail': 'leu@altered-state.edu',
   'username': 'Lou Scene'}}]

mgf_spectra_short = [{'intensity array': makeCA(mgf_int[0]),
  'charge array': makeCA(mgf_ch[0]),
  'm/z array': makeCA(mgf_mz[0]),
  'params': {'pepmass': (983.6, None), 'title': 'Spectrum 1',
            'charge': [2]}},
 {'intensity array': makeCA(mgf_int[1]),
  'm/z array': makeCA(mgf_mz[1]),
  'charge array': makeCA(mgf_ch[1]),
  'params': {'pepmass': (1084.9, 1234.0),
   'rtinseconds': '25',
   'scans': '3',
   'title': 'Spectrum 2'}}]

mgf_spectra_short_no_charges = deepcopy(mgf_spectra_short)
for s in mgf_spectra_short_no_charges:
    del s['charge array']
mgf_spectra_long_no_charges = deepcopy(mgf_spectra_long)
for s in mgf_spectra_long_no_charges:
    del s['charge array']

mgf_spectra_lists = deepcopy(mgf_spectra_long)
for s in mgf_spectra_lists:
    for key in ['m/z array', 'intensity array', 'charge array']:
        s[key] = list(s[key])

tandem_spectra = [{'act': '0',
  'expect': 1.5e-07,
  'fI': 48232.2,
  'id': '11745',
  'maxI': 4823220.0,
  'mh': 800.418907,
  'protein': [{'expect': -989.8,
    'file': {'URL': '/home/lab006/fasta/uniprot_sprot.fasta',
     'type': 'peptide'},
    'id': '11745.1',
    'label': 'sp|P35579|MYH9_HUMAN Myosin-9 OS=Homo sapiens GN=MYH9 PE=1 SV=4',
    'note': 'sp|P35579|MYH9_HUMAN Myosin-9 OS=Homo sapiens GN=MYH9 PE=1 SV=4',
    'peptide': {'b_ions': 2,
     'b_score': 8.2,
     'delta': 0.0,
     'end': 14,
     'expect': 1.5e-07,
     'hyperscore': 16.4,
     'id': '11745.1.1',
     'mh': 800.4189,
     'missed_cleavages': 0,
     'nextscore': 16.4,
     'post': 'NFIN',
     'pre': 'AADK',
     'seq': 'YLYVDK',
     'start': 9,
     'y_ions': 3,
     'y_score': 11.8},
    'sumI': 8.29,
    'uid': '249282'},
   {'expect': -784.7,
    'file': {'URL': '/home/lab006/fasta/uniprot_sprot.fasta',
     'type': 'peptide'},
    'id': '11745.2',
    'label': 'sp|Q258K2|MYH9_CANFA Myosin-9 OS=Canis familiaris GN=MYH9 PE=2 SV=1',
    'note': 'sp|Q258K2|MYH9_CANFA Myosin-9 OS=Canis familiaris GN=MYH9 PE=2 SV=1',
    'peptide': {'b_ions': 2,
     'b_score': 8.2,
     'delta': 0.0,
     'end': 14,
     'expect': 1.5e-07,
     'hyperscore': 16.4,
     'id': '11745.2.1',
     'mh': 800.4189,
     'missed_cleavages': 0,
     'nextscore': 16.4,
     'post': 'NFIN',
     'pre': 'AADK',
     'seq': 'YLYVDK',
     'start': 9,
     'y_ions': 3,
     'y_score': 11.8},
    'sumI': 8.24,
    'uid': '249280'},
   {'expect': -660.7,
    'file': {'URL': '/home/lab006/fasta/uniprot_sprot.fasta',
     'type': 'peptide'},
    'id': '11745.3',
    'label': 'sp|Q8VDD5|MYH9_MOUSE Myosin-9 OS=Mus musculus GN=Myh9 PE=1 SV=4',
    'note': 'sp|Q8VDD5|MYH9_MOUSE Myosin-9 OS=Mus musculus GN=Myh9 PE=1 SV=4',
    'peptide': {'b_ions': 2,
     'b_score': 8.2,
     'delta': 0.0,
     'end': 14,
     'expect': 1.5e-07,
     'hyperscore': 16.4,
     'id': '11745.3.1',
     'mh': 800.4189,
     'missed_cleavages': 0,
     'nextscore': 16.4,
     'post': 'NFIN',
     'pre': 'AADK',
     'seq': 'YLYVDK',
     'start': 9,
     'y_ions': 3,
     'y_score': 11.8},
    'sumI': 8.19,
    'uid': '249283'},
   {'expect': -654.3,
    'file': {'URL': '/home/lab006/fasta/uniprot_sprot.fasta',
     'type': 'peptide'},
    'id': '11745.4',
    'label': 'sp|Q62812|MYH9_RAT Myosin-9 OS=Rattus norvegicus GN=Myh9 PE=1 SV=3',
    'note': 'sp|Q62812|MYH9_RAT Myosin-9 OS=Rattus norvegicus GN=Myh9 PE=1 SV=3',
    'peptide': {'b_ions': 2,
     'b_score': 8.2,
     'delta': 0.0,
     'end': 14,
     'expect': 1.5e-07,
     'hyperscore': 16.4,
     'id': '11745.4.1',
     'mh': 800.4189,
     'missed_cleavages': 0,
     'nextscore': 16.4,
     'post': 'NFIN',
     'pre': 'AADK',
     'seq': 'YLYVDK',
     'start': 9,
     'y_ions': 3,
     'y_score': 11.8},
    'sumI': 8.15,
    'uid': '249284'},
   {'expect': -463.3,
    'file': {'URL': '/home/lab006/fasta/uniprot_sprot.fasta',
     'type': 'peptide'},
    'id': '11745.5',
    'label': 'sp|P14105|MYH9_CHICK Myosin-9 OS=Gallus gallus GN=MYH9 PE=2 SV=1',
    'note': 'sp|P14105|MYH9_CHICK Myosin-9 OS=Gallus gallus GN=MYH9 PE=2 SV=1',
    'peptide': {'b_ions': 2,
     'b_score': 8.2,
     'delta': 0.0,
     'end': 14,
     'expect': 1.5e-07,
     'hyperscore': 16.4,
     'id': '11745.5.1',
     'mh': 800.4189,
     'missed_cleavages': 0,
     'nextscore': 16.4,
     'post': 'NIIN',
     'pre': 'DADK',
     'seq': 'YLYVDK',
     'start': 9,
     'y_ions': 3,
     'y_score': 11.8},
    'sumI': 8.05,
    'uid': '249281'}],
  'rt': 42.0,
  'sumI': 6.93,
  'support': {'fragment ion mass spectrum': {'M+H': 800.419,
    'Xdata': {'units': 'MASSTOCHARGERATIO',
     'values': makeCA(np.array([ 174.759,  249.16 ,  262.135,  277.155,  361.208,  378.203,
        401.716,  440.218,  472.624,  495.27 ,  504.276,  524.271,
        526.277,  637.355]))},
    'Ydata': {'units': 'UNKNOWN',
     'values': makeCA(np.array([   2.,   22.,    3.,   13.,    4.,    1.,    5.,    2.,    2.,
          2.,   10.,  100.,    4.,    6.]))},
    'charge': 2,
    'id': '11745',
    'label': '11745.spectrum',
    'note': 'YLYVDK'},
   'supporting data': {'b ion histogram': {'Xdata': {'units': 'number of ions',
      'values': makeCA(np.array([0, 1, 2, 3]))},
     'Ydata': {'units': 'counts', 'values': makeCA(np.array([346,  64,  21,   0]))},
     'label': '11745.b'},
    'convolution survival function': {'Xdata': {'units': 'score',
      'values': makeCA(np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]))},
     'Ydata': {'units': 'counts',
      'values': makeCA(np.array([351, 351, 351, 309,  99,  20,   1,   0,   0,   0,  80,   0,  43,   0]))},
     'label': '11745.convolute'},
    'hyperscore expectation function': {'Xdata': {'units': 'score',
      'values': makeCA(np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17]))},
     'Ydata': {'units': 'counts',
      'values': makeCA(np.array([350, 350, 350, 308,  98,  19,   0,  81,   0,   0,  80,   3,   0,
        47,   4,   0,  10,   0]))},
     'a0': 4.84111,
     'a1': -0.712472,
     'label': '11745.hyper'},
    'y ion histogram': {'Xdata': {'units': 'number of ions',
      'values': makeCA(np.array([0, 1, 2, 3, 4]))},
     'Ydata': {'units': 'counts', 'values': makeCA(np.array([  2, 381,  38,  10,   0]))},
     'label': '11745.y'}}},
  'z': 2}]
